//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umbraco.dialogs {
    
    public partial class editCell {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.HtmlControls.HtmlTable macroProperties;
        protected System.Web.UI.WebControls.DropDownList tableAlign;
        protected System.Web.UI.WebControls.DropDownList tableVAlign;
    }
}
