tinyMCE.addI18n('it.umbimage_dlg', {
    tab_general: 'Generale',
    tab_appearance: 'Aspetto',
    tab_advanced: 'Avanzate',
    general: 'Generale',
    title: 'Titolo',
    preview: 'Anteprima',
    constrain_proportions: 'Vincola proporzioni',
    langdir: 'Direzione lingua',
    langcode: 'Codice lingua',
    long_desc: 'Descrizione lunga del collegamento',
    style: 'Stile',
    classes: 'Classi',
    ltr: 'Da sinistra a destra',
    rtl: 'Da destra a sinistra',
    id: 'Id',
    map: 'Image map',
    swap_image: 'Swap immagine',
    alt_image: 'Testo alternativo',
    mouseover: 'Mouse over',
    mouseout: 'Mouse out',
    misc: 'Varie',
    example_img: 'Aspetto anteprima immagine',
    missing_alt: 'Sei sicuro di voler continuare senza includere una Descrizione dell'immagine? Se non lo fai l'immagine potrebbe risultare non accessibile per gli utenti con disabilit\u00E0, o per chi utilizza un browser di testo, o per chi naviga senza immagini.',
    dialog_title: 'Inserisci/Modifica immagine',
    src: 'URL immagine',
    alt: 'Descrizione immagine',
    list: 'Immagine lista',
    border: 'Bordo',
    dimensions: 'Dimensioni',
    vspace: 'Spaziatura verticale',
    hspace: 'Spaziatura orizzontale',
    align: 'Allineamento',
    align_baseline: 'Baseline',
    align_top: 'Top',
    align_middle: 'Middle',
    align_bottom: 'Bottom',
    align_texttop: 'Testo superiore',
    align_textbottom: 'Testo inferiore',
    align_left: 'Sinistra',
    align_right: 'Destra',
    image_list: 'Immagine lista'
});
