tinyMCE.addI18n('es.style_dlg',{
title:"Editar Estilo CSS",
apply:"Aplicar",
text_tab:"Texto",
background_tab:"Fondo",
block_tab:"Bloque",
box_tab:"Caja",
border_tab:"Borde",
list_tab:"Lista",
positioning_tab:"Posici\u00F3n",
text_props:"Texto",
text_font:"Fuente",
text_size:"Tama\u00F1o",
text_weight:"Peso",
text_style:"Estilo",
text_variant:"Variante",
text_lineheight:"Ancho de la fila",
text_case:"Min\u00FAs./May\u00FAs.",
text_color:"Color",
text_decoration:"Decorativos",
text_overline:"Subrayado superior",
text_underline:"Subrayado",
text_striketrough:"Tachado",
text_blink:"Parpadeo",
text_none:"Ninguno",
background_color:"Color de fondo",
background_image:"Imagen de fondo",
background_repeat:"Repetici\u00F3n",
background_attachment:"Adjunto",
background_hpos:"Posici\u00F3n horizontal",
background_vpos:"Posici\u00F3n vertical",
block_wordspacing:"Espacio entre palabra",
block_letterspacing:"Espacio entre letra",
block_vertical_alignment:"Alineaci\u00F3n vertical",
block_text_align:"Alineaci\u00F3n del texto",
block_text_indent:"Sangr\u00EDa",
block_whitespace:"Espacio en blanco",
block_display:"Display",
box_width:"Ancho",
box_height:"Alto",
box_float:"Float",
box_clear:"Clear",
padding:"Padding",
same:"Lo mismo en todos",
top:"Arriba",
right:"Derecha",
bottom:"Debajo",
left:"Izquierda",
margin:"Margen",
style:"Estilo",
width:"Ancho",
height:"Alto",
color:"Color",
list_type:"Tipo",
bullet_image:"Imagen de la vi\u00F1eta",
position:"Posici\u00F3n",
positioning_type:"Tipo",
visibility:"Visibilidad",
zindex:"Z-index",
overflow:"Overflow",
placement:"Placement",
clip:"Clip"
});