tinyMCE.addI18n('no.style_dlg',{
title:"Rediger CSS-stil",
apply:"Legg til",
text_tab:"Tekst",
background_tab:"Bakgrunn",
block_tab:"Blokk",
box_tab:"Boks",
border_tab:"Ramme",
list_tab:"Liste",
positioning_tab:"Posisjon",
text_props:"Egenskaper for skrift",
text_font:"Skrifttype",
text_size:"Skriftst\u00F8rrelse",
text_weight:"Skriftvekt",
text_style:"Skriftstil",
text_variant:"Variant",
text_lineheight:"Linjeh\u00F8yde",
text_case:"Kapiteler/minuskaler",
text_color:"Farge",
text_decoration:"Dekorasjon",
text_overline:"Hev skrift",
text_underline:"Senk skrift",
text_striketrough:"Gjennomstrek",
text_blink:"Blink",
text_none:"Ingen",
background_color:"Bakgrunnsfarge",
background_image:"Bakgrunnsbilde",
background_repeat:"Gjenta",
background_attachment:"Vedlegg",
background_hpos:"Horisontal posisjon",
background_vpos:"Vertikal posisjon",
block_wordspacing:"Ordmellomrom",
block_letterspacing:"Bokstavmellomrom",
block_vertical_alignment:"Vertikal justering",
block_text_align:"Justering",
block_text_indent:"Innrykk",
block_whitespace:"Mellomrom",
block_display:"Framskyvning",
box_width:"Bredde",
box_height:"H\u00F8yde",
box_float:"Flyt",
box_clear:"Slett",
padding:"Utfylling",
same:"Likt i alle",
top:"Topp",
right:"H\u00F8yre",
bottom:"Bunn",
left:"Venstre",
margin:"Marg",
style:"Stil",
width:"Bredde",
height:"H\u00F8yd",
color:"Farge",
list_type:"Type",
bullet_image:"Kulepunktbilde",
position:"Posisjon",
positioning_type:"Type",
visibility:"Synlighet",
zindex:"Z-indeks",
overflow:"Overfylt",
placement:"Plassering",
clip:"Klipp"
});