// RO lang variables

tinyMCE.addToLang('',{
bold_desc : 'Bold (Ctrl+B)',
italic_desc : 'Italic (Ctrl+I)',
underline_desc : 'Subliniat (Ctrl+U)',
striketrough_desc : 'T&#259;iat',
justifyleft_desc : 'Aliniere la st&#226;nga',
justifycenter_desc : 'Centrat',
justifyright_desc : 'Alinere la dreapta',
justifyfull_desc : 'Aliniere integral&#259;',
bullist_desc : 'List&#259; neordonat&#259;',
numlist_desc : 'List&#259; ordonat&#259;',
outdent_desc : 'De-indentare',
indent_desc : 'Indentare',
undo_desc : 'Revenire cu un pas &#238;napoi (Ctrl+Z)',
redo_desc : 'Revenire cu un pas &#238;nainte (Ctrl+Y)',
link_desc : 'Insereaz&#259;/editeaz&#259; leg&#259;tur&#259;',
unlink_desc : '&#350;terge leg&#259;tura',
image_desc : 'Insereaz&#259;/editeaz&#259; imagine',
cleanup_desc : 'Cur&#259;&#355;&#259; cod ne&#238;ngrijit',
focus_alert : 'O instan&#355;&#259; de editare trebuie s&#259; fie activ&#259; &#238;nainte de folosirea acestei comenzi.',
edit_confirm : 'Vrei s&#259; folose&#351;ti modul WYSIWYG pentru aceast&#259; zon&#259; de text?',
insert_link_title : 'Insereaz&#259;/editeaz&#259; leg&#259;tur&#259;',
insert : 'Insereaz&#259;',
update : 'Actualizeaz&#259;',
cancel : 'Anulare',
insert_link_url : 'URL leg&#259;tur&#259;',
insert_link_target : '&#354;int&#259; leg&#259;tur&#259;',
insert_link_target_same : 'Deschide leg&#259;tura &#238;n aceea&#351;i fereastr&#259;',
insert_link_target_blank : 'Deschide leg&#259;tura &#238;ntr-o fereastr&#259; nou&#259;',
insert_image_title : 'Insereaz&#259;/editeaz&#259; imagine',
insert_image_src : 'URL imagine',
insert_image_alt : 'Descriere imagine',
help_desc : 'Ajutor',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copierea/T&#259;ierea/Lipirea nu sunt disponibile &#238;n Mozilla &#351;i Firefox.\nVrei mai multe informa&#355;ii despre acest lucru?',
popup_blocked : 'Ne pare r&#259;u, dar am observat c&#259; componenta de blocare a popup-urilor a dezactivat o fereastr&#259; care asigur&#259; func&#355;ionalitatea aplica&#355;iei. Va trebui s&#259; dezactivezi blocarea de popup-uri pe acest portal, pentru a putea folosi acest instrument la &#238;ntreaga lui capacitate.'
});
