// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'I forte (Ctrl+B)',
italic_desc : 'Italik (Ctrl+I)',
underline_desc : 'I nenvizuar (Ctrl+U)',
striketrough_desc : 'Strikethrough',
justifyleft_desc : 'Ne te majte',
justifycenter_desc : 'Ne mes',
justifyright_desc : 'Ne te djathte',
justifyfull_desc : 'Justifiko',
bullist_desc : 'Liste e parenditur',
numlist_desc : 'Liste e renditur',
outdent_desc : 'Terhiq',
indent_desc : 'Shty',
undo_desc : 'Ç\'bej (Ctrl+Z)',
redo_desc : 'Ri-bej (Ctrl+Y)',
link_desc : 'Nderfut /ndrysho lidhjen',
unlink_desc : 'Ç\'lidh',
image_desc : 'Nderfut /ndrysho imazhin',
cleanup_desc : 'Pastor kodin problematik',
focus_alert : 'fokuso nje instance editori pastaj kliko.',
edit_confirm : 'A do te perdoresh tinyMce?',
insert_link_title : 'Nderfut /ndrysho lidhjen',
insert : 'Nderfut',
update : 'Ndrysho',
cancel : 'Kthehu',
insert_link_url : 'URL e lidhjes',
insert_link_target : 'Objektivi',
insert_link_target_same : 'Hape lidhjen ne po ate dritare',
insert_link_target_blank : 'Hape lidhjen ne dritare te re',
insert_image_title : 'Nderfut /ndrysho imazhin',
insert_image_src : 'URL e imazhit',
insert_image_alt : 'Pershkrimi i imazhit',
help_desc : 'Ndihme',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : '?',
popup_blocked : 'Shiko popup blocker - in.'
});