// Serbian lang variables

tinyMCE.addToLang('',{
bold_desc : 'Podebljano (Ctrl+B)',
italic_desc : 'Kurziv (Ctrl+I)',
underline_desc : 'Podvučeno (Ctrl+U)',
striketrough_desc : 'Linija preko teksta',
justifyleft_desc : 'Ravnanje uz levu ivicu',
justifycenter_desc : 'Ravnanje na centar',
justifyright_desc : 'Ravnanje uz desnu ivicu',
justifyfull_desc : 'Ravnanje uz levu i desnu ivicu',
bullist_desc : 'Nesortirana lista',
numlist_desc : 'Sortirana list',
outdent_desc : 'Outdent',
indent_desc : 'Indent',
undo_desc : 'Undo (Ctrl+Z)',
redo_desc : 'Redo (Ctrl+Y)',
link_desc : 'Ubacivanje/menjanje linka',
unlink_desc : 'Skidanje linka',
image_desc : 'Ubacivanje/menjanje slike',
cleanup_desc : 'Čišćenje lošeg koda',
focus_alert : 'Editor mora imati fokus pre korišćenja ove komande.',
edit_confirm : 'Da li želite da koristite obogaćeni modus za ovo tekst polje?',
insert_link_title : 'Ubacivanje/menjajne linka',
insert : 'Ubacivanje',
update : 'Ažuriranje',
cancel : 'Nazad',
insert_link_url : 'Link URL',
insert_link_target : 'Mesto otvaranja',
insert_link_target_same : 'Otvaranje u istom prozoru',
insert_link_target_blank : 'Otvaranje u novom prozoru',
insert_image_title : 'Ubacivanje/menjanje slike',
insert_image_src : 'Link za sliku',
insert_image_alt : 'Opis slike',
help_desc : 'Pomoć',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Copy/Cut/Paste nije moguće u Mozilli i Firefoxu.\nDa li želite više informacija o ovom problemu?',
popup_blocked : 'Izvinjavamo se ali primetili smo da je Vaš program za blokiranje pop-up prozora blokirao prozor koji je potreban aplikaciji. Morate ukinuti blokiranje pop-up prozora na ovom sajtu da bi koristili aplikaciju u potpunosti.'
});
