// Ukrainian translation

tinyMCE.addToLang('',{
bold_desc : 'Жирний (Ctrl+B)',
italic_desc : 'Курсив (Ctrl+I)',
underline_desc : 'Підкреслений (Ctrl+U)',
striketrough_desc : 'Перекреслений',
justifyleft_desc : 'Вирівнювання вліво',
justifycenter_desc : 'Вирівнювання до центру',
justifyright_desc : 'Вирівнювання вправо',
justifyfull_desc : 'Рівномірне заповнення',
bullist_desc : 'Маркірований список',
numlist_desc : 'Нумерований список',
outdent_desc : 'Зменшити відступ',
indent_desc : 'Збільшити відступ',
undo_desc : 'Скасувати (Ctrl+Z)',
redo_desc : 'Повернути (Ctrl+Y)',
link_desc : 'Вставити/змінити посилання',
unlink_desc : 'Прибрати посилання',
image_desc : 'Вставити/змінити зображення',
cleanup_desc : 'Підчистити надлишковий код',
focus_alert : 'Для використання команди маєте перебувати у полі редактора.',
edit_confirm : 'Чи хочете редагувати у візуальному (WYSIWYG) режимі?',
insert_link_title : 'Вставити/змінити посилання',
insert : 'Вставити',
update : 'Застосувати',
cancel : 'Скасувати',
insert_link_url : 'Адреса посилання',
insert_link_target : 'Відкрити в...:',
insert_link_target_same : 'тому самому вікні',
insert_link_target_blank : 'новому вікні',
insert_image_title : 'Вставити/змінити зображення',
insert_image_src : 'Адреса картинки',
insert_image_alt : 'Опис картинки',
help_desc : 'Допомога',
bold_img : "bold_ru.gif",
italic_img : "italic_ru.gif",
underline_img : "underline_ru.gif",
clipboard_msg : 'Копіювати/Вирізати/Вставити недоступні для Mozilla і Firefox.\nХочете дізнатися про це докладніше?',
popup_blocked : 'Вибачте, але у Вашому браузері заблоковані спливаючі вікна. Щоб користуватися всіма можливостями редактора, треба відключити для цього сайту блокування спливаючих вікон.'
});
