// Ukrainian translation

tinyMCE.addToLang('',{
bold_desc : 'Жирний (Ctrl+B)',
italic_desc : 'Курсив (Ctrl+I)',
underline_desc : 'П╕дкреслений (Ctrl+U)',
striketrough_desc : 'Перекреслений',
justifyleft_desc : 'Вир╕внювання вл╕во',
justifycenter_desc : 'Вир╕внювання до центру',
justifyright_desc : 'Вир╕внювання вправо',
justifyfull_desc : 'Р╕вном╕рне заповнення',
bullist_desc : 'Марк╕рований список',
numlist_desc : 'Нумерований список',
outdent_desc : 'Зменшити в╕дступ',
indent_desc : 'Зб╕льшити в╕дступ',
undo_desc : 'Скасувати (Ctrl+Z)',
redo_desc : 'Повернути (Ctrl+Y)',
link_desc : 'Вставити/зм╕нити посилання',
unlink_desc : 'Прибрати посилання',
image_desc : 'Вставити/зм╕нити зображення',
cleanup_desc : 'П╕дчистити надлишковий код',
focus_alert : 'Для використання команди ма╓те перебувати у пол╕ редактора.',
edit_confirm : 'Чи хочете редагувати у в╕зуальному (WYSIWYG) режим╕?',
insert_link_title : 'Вставити/зм╕нити посилання',
insert : 'Вставити',
update : 'Застосувати',
cancel : 'Скасувати',
insert_link_url : 'Адреса посилання',
insert_link_target : 'В╕дкрити в...:',
insert_link_target_same : 'тому самому в╕кн╕',
insert_link_target_blank : 'новому в╕кн╕',
insert_image_title : 'Вставити/зм╕нити зображення',
insert_image_src : 'Адреса картинки',
insert_image_alt : 'Опис картинки',
help_desc : 'Допомога',
bold_img : "bold_ru.gif",
italic_img : "italic_ru.gif",
underline_img : "underline_ru.gif",
clipboard_msg : 'Коп╕ювати/Вир╕зати/Вставити недоступн╕ для Mozilla ╕ Firefox.\nХочете д╕знатися про це докладн╕ше?',
popup_blocked : 'Вибачте, але у Вашому браузер╕ заблокован╕ спливаюч╕ в╕кна. Щоб користуватися вс╕ма можливостями редактора, треба в╕дключити для цього сайту блокування спливаючих в╕кон.'
});
