// Vietnamese lang variables - Đỗ Xuân Tiến - tiendx2002@yahoo.com Việt hóa

tinyMCE.addToLang('',{
bold_desc : 'Đậm (Ctrl+B)',
italic_desc : 'Nghiêng (Ctrl+I)',
underline_desc : 'Gạch chân (Ctrl+U)',
striketrough_desc : 'Gạch ngang',
justifyleft_desc : 'Căn lề trái',
justifycenter_desc : 'Căn lề giữa',
justifyright_desc : 'Căn lề phải',
justifyfull_desc : 'Căn lề đều hai bên',
bullist_desc : 'Danh sách không sắp xếp thứ tự',
numlist_desc : 'Danh sách có sắp xếp thứ tự',
outdent_desc : 'Nhô ra',
indent_desc : 'Thụt vào',
undo_desc : 'Quay lại một thao tác (Ctrl+Z)',
redo_desc : 'Thực hiện lại một thao tác (Ctrl+Y)',
link_desc : 'Thêm/sửa liên kết',
unlink_desc : 'Hủy liên kết',
image_desc : 'Thêm/sửa ảnh',
cleanup_desc : 'Xóa sạch các mã lộn xộn',
focus_alert : 'Cần nhấn chuột vào bên trong ô nhập trước khi sử dụng lệnh này.',
edit_confirm : 'Bạn có muốn dùng chế độ WYSIWYG (thấy gì có nấy) cho ô nhập này?',
insert_link_title : 'Thêm/sửa liên kết',
insert : 'Thêm',
update : 'Cập_nhật',
cancel : 'Hủy bỏ',
insert_link_url : 'Địa chỉ liên kết',
insert_link_target : 'Mục tiêu',
insert_link_target_same : 'Mở liên kết trong cùng cửa sổ',
insert_link_target_blank : 'Mở liên kết trong cửa sổ mới',
insert_image_title : 'Thêm/sửa ảnh',
insert_image_src : 'Địa chỉ ảnh',
insert_image_alt : 'Mô tả ảnh',
help_desc : 'Trợ giúp',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Trên Mozilla và Firefox không sử dụng được các thao tác Sao chép/Cắt/Dán. \nBạn cần thêm thông tin về điều này?',
popup_blocked : 'Xin lỗi, nhưng chúng tôi thấy bộ khóa các cửa sổ bật ra (popup-blocker) của bạn đã khóa một cửa sổ cung cấp chức năng ứng dụng. Bạn cần tắt chế độ khóa cửa sổ bật ra cho trang web này để sử dụng hết các chức năng của công cụ này.'
});
