using Umbraco.Cms.Infrastructure.Persistence.DatabaseModelDefinitions;

namespace Umbraco.Cms.Infrastructure.Migrations.Expressions.Common;

/// <summary>
/// Provides a fluent builder interface for configuring column options within a database migration expression.
/// </summary>
public interface IColumnOptionBuilder<out TNext, out TNextFk> : IFluentBuilder
    where TNext : IFluentBuilder
    where TNextFk : IFluentBuilder
{
    /// <summary>
    /// Sets the default value for the column using the specified <see cref="SystemMethods"/> method.
    /// </summary>
    /// <param name="method">The <see cref="SystemMethods"/> value representing the system method to use as the column's default value.</param>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext WithDefault(SystemMethods method);

    /// <summary>
    /// Specifies a default value for the column being defined.
    /// </summary>
    /// <param name="value">The default value to assign to the column if no value is provided during insert operations.</param>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext WithDefaultValue(object value);

    /// <summary>
    /// Marks the column as an identity column, meaning its value will be automatically generated by the database.
    /// </summary>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext Identity();

    /// <summary>
    /// Marks the column as indexed by creating a non-unique index on it.
    /// </summary>
    /// <returns>The next builder in the expression chain.</returns>
    TNext Indexed();

    /// <summary>
    /// Marks the column as indexed and assigns the specified index name.
    /// </summary>
    /// <param name="indexName">The name to assign to the created index.</param>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext Indexed(string indexName);

    /// <summary>
    /// Specifies that the column should be defined as a primary key in the database schema.
    /// </summary>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext PrimaryKey();

    /// <summary>
    /// Sets a primary key constraint on the column with the specified constraint name.
    /// </summary>
    /// <param name="primaryKeyName">The name to assign to the primary key constraint.</param>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext PrimaryKey(string primaryKeyName);

    /// <summary>
    /// Sets the column as nullable, allowing it to store null values.
    /// </summary>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext Nullable();

    /// <summary>Marks the column as not nullable.</summary>
    /// <returns>The next step in the column option builder chain.</returns>
    TNext NotNullable();

    /// <summary>
    /// Specifies that the column should have a unique constraint applied, ensuring all values in the column are distinct.
    /// </summary>
    /// <returns>The next step in the column option builder expression chain.</returns>
    TNext Unique();

    /// <summary>
    /// Applies a unique constraint to the column using the specified index name, ensuring all values in the column are distinct.
    /// </summary>
    /// <param name="indexName">The name of the unique index to create for the column.</param>
    /// <returns>The next step in the column option builder expression chain.</returns>
    TNext Unique(string indexName);

    /// <summary>
    /// Specifies a foreign key constraint for the current column, referencing a primary key in another table.
    /// </summary>
    /// <param name="primaryTableName">The name of the table containing the primary key to reference.</param>
    /// <param name="primaryColumnName">The name of the primary key column in the referenced table.</param>
    /// <returns>An object representing the next step in the column option builder chain, allowing further configuration.</returns>
    TNextFk ForeignKey(string primaryTableName, string primaryColumnName);

    /// <summary>
    /// Specifies a foreign key constraint for the current column, referencing a primary key in another table.
    /// </summary>
    /// <param name="foreignKeyName">The name of the foreign key constraint.</param>
    /// <param name="primaryTableName">The name of the table containing the primary key to reference.</param>
    /// <param name="primaryColumnName">The name of the primary key column in the referenced table.</param>
    /// <returns>An object representing the next step in the column option builder chain, allowing further configuration.</returns>
    TNextFk ForeignKey(string foreignKeyName, string primaryTableName, string primaryColumnName);

    /// <summary>
    /// Specifies a foreign key constraint for the current column, referencing a primary key in another table.
    /// </summary>
    /// <param name="foreignKeyName">The name of the foreign key constraint.</param>
    /// <param name="primaryTableSchema">The schema of the table containing the primary key to reference.</param>
    /// <param name="primaryTableName">The name of the table containing the primary key to reference.</param>
    /// <param name="primaryColumnName">The name of the primary key column in the referenced table.</param>
    /// <returns>An object representing the next step in the column option builder chain, allowing further configuration.</returns>
    TNextFk ForeignKey(
        string foreignKeyName,
        string primaryTableSchema,
        string primaryTableName,
        string primaryColumnName);

    /// <summary>
    /// Configures the current column as a foreign key referencing another table.
    /// </summary>
    /// <returns>The next step in the column option builder chain.</returns>
    TNextFk ForeignKey();

    /// <summary>
    /// Specifies that this column is the target of a foreign key from another table.
    /// </summary>
    /// <param name="foreignTableName">The name of the table containing the foreign key that references this column.</param>
    /// <param name="foreignColumnName">The name of the column in the foreign table that references this column.</param>
    /// <returns>An object representing the next step in the migration expression.</returns>
    TNextFk ReferencedBy(string foreignTableName, string foreignColumnName);

    /// <summary>
    /// Specifies that this column is referenced by a foreign key constraint from another table.
    /// </summary>
    /// <param name="foreignKeyName">The name of the foreign key constraint that references this column.</param>
    /// <param name="foreignTableName">The name of the table containing the foreign key.</param>
    /// <param name="foreignColumnName">The name of the column in the foreign table that references this column.</param>
    /// <returns>The builder for configuring the foreign key relationship.</returns>

    TNextFk ReferencedBy(string foreignKeyName, string foreignTableName, string foreignColumnName);

    /// <summary>
    /// Specifies that this column is the target of a foreign key from another table.
    /// </summary>
    /// <param name="foreignKeyName">The name of the foreign key constraint.</param>
    /// <param name="foreignTableSchema">The schema of the table containing the foreign key that references this column.</param>
    /// <param name="foreignTableName">The name of the table containing the foreign key that references this column.</param>
    /// <param name="foreignColumnName">The name of the column in the foreign table that references this column.</param>
    /// <returns>An object representing the next step in the migration expression.</returns>
    TNextFk ReferencedBy(
        string foreignKeyName,
        string foreignTableSchema,
        string foreignTableName,
        string foreignColumnName);
}
