using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Models.ContentEditing;
using Umbraco.Cms.Core.Services;
using Umbraco.Extensions;

namespace Umbraco.Cms.Tests.Common.Factories;

// Disclaimer: Based on code generated by Claude code.
// Most likely not complete, but the logic looks sound.
public class ContentEditingModelFactory : IContentEditingModelFactory
{
    private readonly ITemplateService _templateService;

    public ContentEditingModelFactory(ITemplateService templateService)
    {
        _templateService = templateService;
    }

    public async Task<ContentUpdateModel> CreateFromAsync(IContent content)
    {
        {
            var templateKey = content.TemplateId.HasValue
                ? (await _templateService.GetAsync(content.TemplateId.Value))?.Key
                : null;
            var model = new ContentUpdateModel { TemplateKey = templateKey };
            var properties = new List<PropertyValueModel>();
            var variants = new List<VariantModel>();

            MapProperties(content, properties);

            MapNames(content, variants);

            model.Properties = properties;
            model.Variants = variants;
            return model;
        }
    }

    private static void MapNames(IContent content, List<VariantModel> variants)
    {
        if (content.ContentType.VariesByCulture())
        {
            variants.AddRange(content
                .AvailableCultures
                .Select(culture =>
                {
                    var variantName = content.GetCultureName(culture);
                    return variantName.IsNullOrWhiteSpace()
                        ? null
                        : new VariantModel { Culture = culture, Name = variantName };
                })
                .WhereNotNull());
        }
        else
        {
            variants.Add(new VariantModel { Culture = null, Name = content.Name ?? string.Empty });
        }
    }

    private static void MapProperties(IContent content, List<PropertyValueModel> properties)
    {
        // Handle properties
        foreach (var property in content.Properties)
        {
            var propertyVariesByCulture = property.PropertyType.VariesByCulture();
            var propertyVariesBySegment = property.PropertyType.VariesBySegment();

            // Get all property values from the property's Values collection
            foreach (var propertyValue in property.Values)
            {
                if (propertyValue.EditedValue != null)
                {
                    properties.Add(new PropertyValueModel
                    {
                        Alias = property.Alias,
                        Value = propertyValue.EditedValue,
                        Culture = propertyVariesByCulture ? propertyValue.Culture : null,
                        Segment = propertyVariesBySegment ? propertyValue.Segment : null,
                    });
                }
            }

            // Fallback: if no values found in the Values collection, try the traditional approach
            if (!property.Values.Any())
            {
                if (propertyVariesByCulture && content.AvailableCultures.Any())
                {
                    // Handle culture variants
                    foreach (var culture in content.AvailableCultures)
                    {
                        var cultureValue = property.GetValue(culture);
                        if (cultureValue != null)
                        {
                            properties.Add(new PropertyValueModel
                            {
                                Alias = property.Alias, Value = cultureValue, Culture = culture, Segment = null,
                            });
                        }
                    }

                    // Also add the invariant value if it exists
                    var invariantValue = property.GetValue();
                    if (invariantValue != null)
                    {
                        properties.Add(new PropertyValueModel
                        {
                            Alias = property.Alias, Value = invariantValue, Culture = null, Segment = null,
                        });
                    }
                }
                else
                {
                    // Handle invariant properties
                    var value = property.GetValue();
                    if (value != null)
                    {
                        properties.Add(new PropertyValueModel
                        {
                            Alias = property.Alias, Value = value, Culture = null, Segment = null,
                        });
                    }
                }
            }
        }
    }
}
