// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api;
namespace UmbracoDeliveryClient.Generated.Umbraco.Delivery
{
    /// <summary>
    /// Builds and executes requests for operations under \umbraco\delivery
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeliveryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The api property</summary>
        public global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.ApiRequestBuilder Api
        {
            get => new global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.ApiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.DeliveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/umbraco/delivery", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.DeliveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/umbraco/delivery", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
