tinyMCE.addI18n('de.style_dlg',{
title:"CSS-Styles bearbeiten",
apply:"\u00DCbernehmen",
text_tab:"Text",
background_tab:"Hintergrund",
block_tab:"Block",
box_tab:"Box",
border_tab:"Rahmen",
list_tab:"Liste",
positioning_tab:"Positionierung",
text_props:"Text",
text_font:"Schriftart",
text_size:"Gr\u00F6\u00DFe",
text_weight:"Dicke",
text_style:"Stil",
text_variant:"Variante",
text_lineheight:"Zeilenh\u00F6he",
text_case:"Schreibung",
text_color:"Farbe",
text_decoration:"Gestaltung",
text_overline:"\u00FCberstrichen",
text_underline:"unterstrichen",
text_striketrough:"durchgestrichen",
text_blink:"blinkend",
text_none:"keine",
background_color:"Hintergrundfarbe",
background_image:"Hintergrundbild",
background_repeat:"Wiederholung",
background_attachment:"Wasserzeicheneffekt",
background_hpos:"Position X",
background_vpos:"Position Y",
block_wordspacing:"Wortabstand",
block_letterspacing:"Buchstabenabstand",
block_vertical_alignment:"Vertikale Ausrichtung",
block_text_align:"Ausrichtung",
block_text_indent:"Einr\u00FCckung",
block_whitespace:"Automatischer Umbruch",
block_display:"Umbruchverhalten",
box_width:"Breite",
box_height:"H\u00F6he",
box_float:"Umflie\u00DFung",
box_clear:"Umflie\u00DFung verhindern",
padding:"Innerer Abstand",
same:"Alle gleich",
top:"Oben",
right:"Rechts",
bottom:"Unten",
left:"Links",
margin:"\u00C4u\u00DFerer Abstand",
style:"Format",
width:"Breite",
height:"H\u00F6he",
color:"Textfarbe",
list_type:"Listenpunkt-Art",
bullet_image:"Listenpunkt-Grafik",
position:"Positionierung",
positioning_type:"Art der Positionierung",
visibility:"Sichtbar",
zindex:"Z-Wert",
overflow:"Verhalten bei \u00DCbergr\u00F6\u00DFe",
placement:"Platzierung",
clip:"Ausschnitt"
});