tinyMCE.addI18n('it.style_dlg',{
title:"Modifica stile CSS",
apply:"Applica",
text_tab:"Testo",
background_tab:"Sfondo",
block_tab:"Blocco",
box_tab:"Contenitore",
border_tab:"Bordi",
list_tab:"Liste",
positioning_tab:"Posizionamento",
text_props:"Testo",
text_font:"Carattere",
text_size:"Dimensione",
text_weight:"Spessore",
text_style:"Stile",
text_variant:"Variante",
text_lineheight:"Altezza linea",
text_case:"Tipo",
text_color:"Colore",
text_decoration:"Decorazione",
text_overline:"sopralineato",
text_underline:"sottolineato",
text_striketrough:"barrato",
text_blink:"lampeggiante",
text_none:"nessuna",
background_color:"Colore sfondo",
background_image:"Immagine sfondo",
background_repeat:"Repetizione",
background_attachment:"Allegato",
background_hpos:"Posizione orizzontale",
background_vpos:"Posizione verticale",
block_wordspacing:"Spaziatura parole",
block_letterspacing:"Spaziatura caratteri",
block_vertical_alignment:"Allineamento verticale",
block_text_align:"Allineamento testo",
block_text_indent:"Indentazione testo",
block_whitespace:"Whitespace",
block_display:"Visualizzazione",
box_width:"Larghezza",
box_height:"Altezza",
box_float:"Float",
box_clear:"Clear",
padding:"Spazio dal bordo",
same:"Uguale per tutti",
top:"Superiore",
right:"Destro",
bottom:"Inferiore",
left:"Sinistro",
margin:"Margine",
style:"Stile",
width:"Larghezza",
height:"Altezza",
color:"Colore",
list_type:"Tipo",
bullet_image:"Immagine bullet",
position:"Posizione",
positioning_type:"Tipo",
visibility:"Visibilit\u00E0",
zindex:"Z-index",
overflow:"Overflow",
placement:"Piazzamento",
clip:"Clip"
});