[
    'angular',
    'app',
    'jquery',
    'jqueryCookie',
    'bootstrap',
    'umbraco.resources',
    'umbraco.directives',
    'umbraco.filters',
    'umbraco.services',
    'umbraco.controllers',
    'sample.propertyeditor.controller',
    'sampletwo.propertyeditor.controller',
    'routes'
]