// Greek lang variables by Jacaranda Bill
// Revised by Dimitris Giannitsaros / MediSign SA

tinyMCE.addToLang('',{
bold_desc : 'Έντονη γραφή',
italic_desc : 'Πλάγια γραφή',
underline_desc : 'Υπογράμμιση',
striketrough_desc : 'διακριτή διαγραφή',
justifyleft_desc : 'Στοίχιση αριστερά',
justifycenter_desc : 'Στοίχιση στο κέντρο',
justifyright_desc : 'Στοίχιση δεξιά',
justifyfull_desc : 'Πλήρης στοίχιση',
bullist_desc : 'Κουκκίδες',
numlist_desc : 'Αρίθμηση',
outdent_desc : 'Μείωση εσοχής',
indent_desc : 'Αύξηση εσοχής',
undo_desc : 'Αναίρεση',
redo_desc : 'Ακύρωση αναίρεσης',
link_desc : 'δημιουργία/διόρθωση υπερ-σύνδεσης',
unlink_desc : 'διαγραφή υπερ-σύνδεσης',
image_desc : 'εισαγωγή/διόρθωση εικόνας',
cleanup_desc : 'Καθάρισμα κώδικα',
focus_alert : 'Πρέπει να υπάρχει ενεργός κάποιος επεξεργαστής κειμένου πριν να χρησιμοποιήσετε αυτή την εντολή.',
edit_confirm : 'Θέλετε να χρησιμοποιήσετε την κατάσταση WYSIWYG για το συγκεκριμένο πλαίσιο κειμένου;',
insert_link_title : 'δημιουργία/διόρθωση υπερ-σύνδεσης',
insert : 'εισαγωγή',
update : 'εισαγωγή',
cancel : 'Ακύρωση',
insert_link_url : 'διεύθυνση',
insert_link_target : 'Στόχος',
insert_link_target_same : 'Άνοιγμα της διεύθυνσης στο ίδιο παράθυρο',
insert_link_target_blank : 'Άνοιγμα της διεύθυνσης σε νέο παράθυρο',
insert_image_title : 'εισαγωγή/διόρθωση εικόνας',
insert_image_src : 'διεύθυνση',
insert_image_alt : 'Περιγραφή',
help_desc : 'Βοήθεια',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Η Αντιγραφή/Αποκοπή/Επικόλληση δεν είναι διαθέσιμες στο Mozilla και στο Firefox.\nΘέλετε πληροφορίες για αυτό το θέμα;',
popup_blocked : 'Ο popup-blocker σας απενεργοποίησε ένα παράθυρο το οποίο χρειάζεται. Θα πρέπει να απενεργοποιήσετε τον popup-blocker σας στο συγκεκριμένο site, ώστε να χρησιμοποιήσετε πλήρως αυτό το εργαλείο.'
});
