// Japanese 日本語 utf-8 language pack 

tinyMCE.addToLang('',{
bold_desc : '太字 (Ctrl+B)',
italic_desc : '斜体 (Ctrl+I)',
underline_desc : '下線 (Ctrl+U)',
striketrough_desc : '取り消し線',
justifyleft_desc : '左揃え',
justifycenter_desc : '中央揃え',
justifyright_desc : '右揃え',
justifyfull_desc : '両端揃え',
bullist_desc : '箇条書き',
numlist_desc : '段落番号',
outdent_desc : 'アウトデント',
indent_desc : 'インデント',
undo_desc : '元に戻す (Ctrl+Z)',
redo_desc : '繰り返し (Ctrl+Y)',
link_desc : 'リンクを挿入・編集',
unlink_desc : 'リンクを外す',
image_desc : 'イメージを挿入',
cleanup_desc : 'コードを整備する',
focus_alert : 'A editor instance must be focused before using this command.',
edit_confirm : 'Do you want to use the WYSIWYG mode for this textarea?',
insert_link_title : 'リンクを挿入・編集',
insert : '挿入',
update : '更新',
cancel : 'キャンセル',
insert_link_url : 'リンクのURL',
insert_link_target : 'ターゲット',
insert_link_target_same : '同じウィンドウでリンクを開く',
insert_link_target_blank : '新しいウィンドウでリンクを開く',
insert_image_title : 'イメージを挿入・編集',
insert_image_src : 'イメージのURL',
insert_image_alt : '代替テキスト',
help_desc : 'ヘルプ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'コピー/切り取る/貼り付けは Mozillaと Firefoxに無効です。\n詳しく表示しますか?',
popup_blocked : 'ポップアップ禁止されているので、ポップアップを有効にしてください。'
});
