tinyMCE.addI18n('it.advimage_dlg',{
tab_general:"Generale",
tab_appearance:"Aspetto",
tab_advanced:"Avanzate",
general:"Generale",
title:"Titolo",
preview:"Anteprima",
constrain_proportions:"Mantieni proporzioni",
langdir:"Direzione testo",
langcode:"codice lingua",
long_desc:"Descrizione del collegamento",
style:"Stile",
classes:"Classe",
ltr:"Sinistra verso destra",
rtl:"Destra verso sinistraa",
id:"Id",
map:"Immagine come mappa",
swap_image:"Sostituisci immagine",
alt_image:"Immagine alternativa",
mouseover:"quando mouse sopra",
mouseout:"quando mouse fuori",
misc:"Impostazioni varie",
example_img:"Anteprima aspetto immagine",
missing_alt:"Sicuro di continuare senza includere una descrizione dell'immagine? Senza di essa l'immagine pu\u00F2 non essere accessibile ad alcuni utenti con disabilit\u00E0, o per coloro che usano un browser testuale oppure che hanno disabilitato la visualizzazione delle immagini nel loro browser.",
dialog_title:"Inserisci/modifica immagine",
src:"URL immagine",
alt:"Descrizione immagine",
list:"Lista immagini",
border:"Bordo",
dimensions:"Dimensioni",
vspace:"Spaziatura verticale",
hspace:"Spaziatura orizzontale",
align:"Allineamento",
align_baseline:"Alla base",
align_top:"In alto",
align_middle:"In mezzo",
align_bottom:"In basso",
align_texttop:"In alto al testo",
align_textbottom:"In basso al testo",
align_left:"A sinistra",
align_right:"A destra",
image_list:"Lista immagini"
});