tinyMCE.addI18n('nl.advimage_dlg',{
tab_general:"Algemeen",
tab_appearance:"Weergave",
tab_advanced:"Geavanceerd",
general:"Algemeen",
title:"Titel",
preview:"Voorbeeld",
constrain_proportions:"Verhouding behouden",
langdir:"Taalrichting",
langcode:"Taalcode",
long_desc:"Uitgebreide beschrijving",
style:"Stijl",
classes:"Klasses",
ltr:"Van links naar rechts",
rtl:"Van rechts naar links",
id:"Id",
map:"Afbeeldingsplattegrond",
swap_image:"Afbeelding wisselen",
alt_image:"Alternatieve afbeeldingen",
mouseover:"Bij muis over",
mouseout:"Bij muis uit",
misc:"Diversen",
example_img:"Voorbeeldweergave",
missing_alt:"Wilt u de afbeelding zonder beschrijving invoegen? De afbeelding wordt dan mogelijk niet opgemerkt door mensen met een visuele handicap, of welke zonder afbeeldingen browsen.",
dialog_title:"Afbeelding invoegen/bewerken",
src:"Bestand/URL",
alt:"Beschrijving",
list:"Lijst",
border:"Rand",
dimensions:"Afmetingen",
vspace:"Verticale ruimte",
hspace:"Horizontale ruimte",
align:"Uitlijning",
align_baseline:"Basislijn",
align_top:"Boven",
align_middle:"Midden",
align_bottom:"Onder",
align_texttop:"Bovenkant tekst",
align_textbottom:"Onderkant tekst",
align_left:"Links",
align_right:"Rechts",
image_list:"Lijst"
});