tinyMCE.addI18n('he.umbraco',{
style_select:"סגנונות",
font_size:"גודל גופן",
fontdefault:"משפחת הגופן",
block:"תבנית",
paragraph:"פסקה",
div:"Div",
address:"כתובת",
pre:"מעוצב מראש",
h1:"כותרת 1",
h2:"כותרת 2",
h3:"כותרת 3",
h4:"כותרת 4",
h5:"כותרת 5",
h6:"כותרת 6",
blockquote:"ציטוט",
code:"קוד",
samp:"קוד לדוגמא",
dt:"הגדרת מונח ",
dd:"תיאור המונח",
bold_desc:"בולט (Ctrl+B)",
italic_desc:"נטוי (Ctrl+I)",
underline_desc:"קו תחתון (Ctrl+U)",
striketrough_desc:"קו חוצה",
justifyleft_desc:"יישר לשמאל",
justifycenter_desc:"יישר למרכז",
justifyright_desc:"יישר לימין",
justifyfull_desc:"יישור מלא",
bullist_desc:"רשימה לא מסודרת",
numlist_desc:"רשימה מסודרת",
outdent_desc:"הסט החוצה",
indent_desc:"הסט פנימה",
undo_desc:"בטל (Ctrl+Z)",
redo_desc:"עשה שוב (Ctrl+Y)",
link_desc:"הוסף\ערוך קישור",
unlink_desc:"בטל קישור",
image_desc:"הוסף\ערוך תמונה",
cleanup_desc:"נקה קוד מבולגן",
code_desc:"ערוך קוד HTML",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"הכנס סרגל אופקי",
removeformat_desc:"הסר עיצוב",
custom1_desc:"Your custom description here",
forecolor_desc:"בחר צבע טקסט",
backcolor_desc:"בחר צבע רקע",
charmap_desc:"הוסף תו מותאם אישית",
visualaid_desc:"החלף מצב קווים מנחים\גורמים בלתי נראים",
anchor_desc:"הוסף\ערוך עוגן",
cut_desc:"גזור",
copy_desc:"העתק",
paste_desc:"הדבק",
image_props_desc:"מאפייני תמונה",
newdocument_desc:"מסמך חדש",
help_desc:"עזרה",
blockquote_desc:"Blockquote",
clipboard_msg:"Copy/Cut/Paste is not available in Mozilla and Firefox.\r\nDo you want more information about this issue?",
path:"Path",
newdocument:"Are you sure you want clear all contents?",
toolbar_focus:"Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X",
more_colors:"עוד צבעים"
});