tinyMCE.addI18n('he.umbraco_dlg',{
about_title:"אודות TinyMCE",
about_general:"אודות",
about_help:"עזרה",
about_license:"רישיון",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Author",
about_version:"Version",
about_loaded:"Loaded plugins",
anchor_title:"הוסף\ערוך עוגן",
anchor_name:"שם העוגן",
code_title:"עורך קוד HTML",
code_wordwrap:"שמירת שוליים",
colorpicker_title:"בחר צבע",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"בחירת צבע",
colorpicker_palette_tab:"לוח צבעים",
colorpicker_palette_title:"לוח צבעים",
colorpicker_named_tab:"צבעים קבועים",
colorpicker_named_title:"צבעים קבועים",
colorpicker_color:"צבע:",
colorpicker_name:"שם:",
charmap_title:"בחר תו מותאם אישית",
image_title:"הוסף\ערוך תמונה",
image_src:"כתובת התמונה",
image_alt:"תיאור התמונה",
image_list:"Image list",
image_border:"גבול",
image_dimensions:"מידות",
image_vspace:"מרווח אנכי",
image_hspace:"מרווח אופקי",
image_align:"יישור",
image_align_baseline:"נקודת התחלה",
image_align_top:"ראש",
image_align_middle:"אמצע",
image_align_bottom:"תחתית",
image_align_texttop:"ראש הטקסט",
image_align_textbottom:"תחתית הטקסט",
image_align_left:"שמאל",
image_align_right:"ימין",
link_title:"הוסף\ערוך לינק",
link_url:"כתובת הקישור",
link_target:"יעד",
link_target_same:"פתח קישור באותו חלון",
link_target_blank:"פתח קישור בחלון חדש",
link_titlefield:"כותרת",
link_is_email:"The URL you entered seems to be an email address, do you want to add the required mailto: prefix?",
link_is_external:"The URL you entered seems to external link, do you want to add the required http:// prefix?",
link_list:"רשימת קישורים"
});