tinyMCE.addI18n('ja.umbraco',{
"underline_desc":"下線 (Ctrl+U)",
"italic_desc":"斜体 (Ctrl+I)",
"bold_desc":"太字 (Ctrl+B)",
dd:"語句の説明",
dt:"語句の定義",
samp:"コードの例",
code:"コード",
blockquote:"引用",
h6:"見出し6",
h5:"見出し5",
h4:"見出し4",
h3:"見出し3",
h2:"見出し2",
h1:"見出し1",
pre:"整形済み",
address:"住所",
div:"div要素",
paragraph:"段落",
block:"書式",
fontdefault:"フォント",
"font_size":"フォントの大きさ",
"style_select":"スタイル",
"anchor_delta_height":"",
"anchor_delta_width":"",
"charmap_delta_height":"",
"charmap_delta_width":"",
"colorpicker_delta_height":"",
"colorpicker_delta_width":"",
"link_delta_height":"",
"link_delta_width":"",
"image_delta_height":"",
"image_delta_width":"",
"more_colors":"その他の色...",
"toolbar_focus":"ツールボタンへ移動 - Alt Q, エディタに移動 - Alt-Z, 要素のパスへ移動 - Alt-X",
newdocument:"本当にすべての内容を消去してよいですか?",
path:"パス",
"clipboard_msg":"Mozilla と Firefox ではコピー/切り取り/貼り付けはできません。\nこの問題の詳細を知りたいですか?",
"blockquote_desc":"引用ブロック",
"help_desc":"ヘルプ",
"newdocument_desc":"新規ドキュメント",
"image_props_desc":"画像の属性",
"paste_desc":"貼り付け (Ctrl+V)",
"copy_desc":"コピー (Ctrl+C)",
"cut_desc":"切り取り (Ctrl+X)",
"anchor_desc":"アンカーの挿入/編集",
"visualaid_desc":"ガイドラインと非表示要素の表示を切替",
"charmap_desc":"特殊文字",
"backcolor_desc":"背景の色",
"forecolor_desc":"文字の色",
"custom1_desc":"説明文を入力してください。",
"removeformat_desc":"書式の解除",
"hr_desc":"水平線の挿入",
"sup_desc":"上付き文字",
"sub_desc":"下付き文字",
"code_desc":"HTMLソースを編集",
"cleanup_desc":"コード整形",
"image_desc":"画像の挿入/編集",
"unlink_desc":"リンクの解除",
"link_desc":"リンクの挿入/編集",
"redo_desc":"やり直し (Ctrl+Y)",
"undo_desc":"元に戻す (Ctrl+Z)",
"indent_desc":"字下げを増やす",
"outdent_desc":"字下げを減らす",
"numlist_desc":"番号付きリスト",
"bullist_desc":"番号なしリスト",
"justifyfull_desc":"両端揃え",
"justifyright_desc":"右揃え",
"justifycenter_desc":"中央揃え",
"justifyleft_desc":"左揃え",
"striketrough_desc":"取り消し線",
"help_shortcut":"ALT-F10 でツールバー、ALT-0 でヘルプ",
"rich_text_area":"リッチテキストエリア",
"shortcuts_desc":"アクセシビリティのヘルプ",
toolbar:"ツールバー"});
