tinyMCE.addI18n('ru.umbraco',{
style_select:"Стиль",
font_size:"Размер",
fontdefault:"Шрифт",
block:"Формат",
paragraph:"Абзац",
div:"Блок",
address:"Адрес",
pre:"Преформатированный",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Заголовок 5",
h6:"Заголовок 6",
blockquote:"Цитата",
code:"Код",
samp:"Пример кода",
dt:"Термин справочника",
dd:"Описание справочника",
bold_desc:"Полужирный (Ctrl+B)",
italic_desc:"Курсив (Ctrl+I)",
underline_desc:"Подчеркнутый (Ctrl+U)",
striketrough_desc:"Зачеркнутый",
justifyleft_desc:"По левому краю",
justifycenter_desc:"По центру",
justifyright_desc:"По правому краю",
justifyfull_desc:"По ширине",
bullist_desc:"Маркированный список",
numlist_desc:"Нумерованный список",
outdent_desc:"Уменьшить отступ",
indent_desc:"Увеличить отступ",
undo_desc:"Отменить (Ctrl+Z)",
redo_desc:"Вернуть (Ctrl+Y)",
link_desc:"Добавить/Изменить ссылку",
unlink_desc:"Удалить ссылку",
image_desc:"Добавить/Изменить изображение",
cleanup_desc:"Очистить лишний код",
code_desc:"Редактировать HTML код",
sub_desc:"Подстрочный",
sup_desc:"Надстрочный",
hr_desc:"Добавить черту",
removeformat_desc:"Очистить формат",
custom1_desc:"Собственное описание",
forecolor_desc:"Цвет текста",
backcolor_desc:"Цвет фона",
charmap_desc:"Добавить символ",
visualaid_desc:"Все знаки",
anchor_desc:"Добавить/Изменить якорь",
cut_desc:"Вырезать",
copy_desc:"Копировать",
paste_desc:"Вставить",
image_props_desc:"Параметры изображения",
newdocument_desc:"Новый документ",
help_desc:"Справка",
blockquote_desc:"Цитата",
clipboard_msg:"Копирование, вырезка и вставка не работают в Firefox.\nХотите получить более подробную информацию?",
path:"Путь",
newdocument:"Вы уверены, что хотите все удалить?",
toolbar_focus:"Перейти на панель кнопок (Alt+Q). Перейти к редактору (Alt+Z). Перейти к элементу пути (Alt+X).",
more_colors:"Другие цвета...",
anchor_delta_height:"",
anchor_delta_width:"",
charmap_delta_height:"",
charmap_delta_width:"",
colorpicker_delta_height:"",
colorpicker_delta_width:"",
link_delta_height:"",
link_delta_width:"",
image_delta_height:"",
image_delta_width:"",
help_shortcut:"Используйте клавиши Alt-F10 для панели инструментов. Используйте Alt-0 для получения справки",
rich_text_area:"Область форматированного текста",
shortcuts_desc:"Справка по доступности",
umbracomacro_desc:"Вставить макрос",
toolbar:"Панель инструментов"});