tinyMCE.addI18n('ru.umbraco_dlg',{
about_title:"Описание TinyMCE",
about_general:"Описание",
about_help:"Помощь",
about_license:"Лицензия",
about_plugins:"Дополнительные модули",
about_plugin:"Модуль",
about_author:"Автор",
about_version:"Версия",
about_loaded:"Подключенные модули",
accessibility_help:"Справка по доступности",
accessibility_usage_title:"Общедоступное применение",
anchor_title:"Параметры якоря",
anchor_name:"Имя якоря",
anchor_invalid:"Укажите корректное название якоря.",
code_title:"Редактор HTML кода",
code_wordwrap:"Перенос строк",
colorpicker_title:"Цвета",
colorpicker_picker_tab:"Спктр",
colorpicker_picker_title:"Цвета",
colorpicker_palette_tab:"Палитра",
colorpicker_palette_title:"Цвета",
colorpicker_named_tab:"Названия",
colorpicker_named_title:"Цвета",
colorpicker_color:"Код:",
colorpicker_name:"Название:",
charmap_title:"Выбор символа",
charmap_usage:"Используйте стрелки вправо и влево для навигации.",
image_title:"Параметры изображения",
image_src:"Адрес",
image_alt:"Описание",
image_list:"Список картинок",
image_border:"Граница",
image_dimensions:"Размер",
image_vspace:"Верт. отступ",
image_hspace:"Гориз. отступ",
image_align:"Выравнивание",
image_align_baseline:"По базовой линии",
image_align_top:"По верхнему краю",
image_align_middle:"По центру",
image_align_bottom:"По нижнему краю",
image_align_texttop:"По верхнему краю текста",
image_align_textbottom:"По нижнему краю текста",
image_align_left:"По левому краю",
image_align_right:"По правому краю",
invalid_color_value:"Некорректное значение цвета",
link_title:"Параметры ссылки",
link_url:"Адрес",
link_target:"Цель",
link_target_same:"Открыть в этом окне",
link_target_blank:"Открыть в новом окне",
link_titlefield:"Заголовок",
link_is_email:"Введенный адрес напоминает электронную почту, добавить mailto: префикс?",
link_is_external:"Введенный адрес напоминает внешнюю ссылку, добавить http:// префикс?",
link_list:"Список ссылок"
"":""});