tinyMCE.addI18n('zh.umbraco',{"underline_desc":"下划线 (Ctrl+U)",
"italic_desc":"斜体 (Ctrl+I)",
"bold_desc":"粗体 (Ctrl+B)",
dd:"定义描述",
dt:"定义条目",
samp:"示例代码",
code:"代码",
blockquote:"块引用",
h6:"标题 6",
h5:"标题 5",
h4:"标题 4",
h3:"标题 3",
h2:"标题 2",
h1:"标题 1",
pre:"预格式化",
address:"地址",
div:"DIV",
paragraph:"段落",
block:"格式化",
fontdefault:"字体",
"font_size":"字号",
"style_select":"样式",
"anchor_delta_height":"",
"anchor_delta_width":"",
"charmap_delta_height":"",
"charmap_delta_width":"",
"colorpicker_delta_height":"",
"colorpicker_delta_width":"",
"link_delta_height":"",
"link_delta_width":"",
"image_delta_height":"",
"image_delta_width":"",
"more_colors":"更多颜色…",
"toolbar_focus":"跳转至工具按钮 - Alt+Q, 跳转至编辑器 - Alt+Z, 跳转至元素路径 - Alt+X",
newdocument:"您确定清除所有内容吗？",
path:"路径",
"clipboard_msg":"复制/剪切/粘贴功能在Mozilla和Firefox中不可用，\n您想了解有关该问题的更多信息吗？",
"blockquote_desc":"块引用",
"help_desc":"帮助",
"newdocument_desc":"新建文档",
"image_props_desc":"图片属性",
"paste_desc":"粘贴 (Ctrl+V)",
"copy_desc":"复制 (Ctrl+C)",
"cut_desc":"剪切 (Ctrl+X)",
"anchor_desc":"插入/编辑锚点",
"visualaid_desc":"显示/隐藏参考线和不可见元素",
"charmap_desc":"插入特殊字符",
"backcolor_desc":"设置背景色",
"forecolor_desc":"文字颜色",
"custom1_desc":"自定义描述",
"removeformat_desc":"清除格式",
"hr_desc":"插入水平线",
"sup_desc":"上标",
"sub_desc":"下标",
"code_desc":"编辑代码",
"cleanup_desc":"净化代码",
"image_desc":"插入/编辑图片",
"unlink_desc":"取消链接",
"link_desc":"插入/编辑链接",
"redo_desc":"撤消 (Ctrl+Y)",
"undo_desc":"恢复 (Ctrl+Z)",
"indent_desc":"增加缩进",
"outdent_desc":"减少缩进",
"numlist_desc":"插入/移除编号列表",
"bullist_desc":"插入/移除非编号列表",
"justifyfull_desc":"两端对齐",
"justifyright_desc":"右对齐",
"justifycenter_desc":"居中",
"justifyleft_desc":"左对齐",
"striketrough_desc":"删除线",
"help_shortcut":"按 ALT+F10 调用工具栏. 按 ALT+0 寻求帮助",
"rich_text_area":"富文本编辑区",
"shortcuts_desc":"小提示",
toolbar:"工具栏"});