// This file is auto-generated by @hey-api/openapi-ts

export { type Options, ping, whatsMyName, whatsTheTimeMrWolf, whoAmI } from './sdk.gen';
export type { ClientOptions, IGranularPermission, IProfile, IReadOnlyUserGroup, Iuser, PingData, PingErrors, PingResponse, PingResponses, UserKind, UserState, WhatsMyNameData, WhatsMyNameErrors, WhatsMyNameResponse, WhatsMyNameResponses, WhatsTheTimeMrWolfData, WhatsTheTimeMrWolfErrors, WhatsTheTimeMrWolfResponse, WhatsTheTimeMrWolfResponses, WhoAmIData, WhoAmIErrors, WhoAmIResponse, WhoAmIResponses } from './types.gen';
