// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.Content;
using UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.Media;
namespace UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2
{
    /// <summary>
    /// Builds and executes requests for operations under \umbraco\delivery\api\v2
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V2RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The content property</summary>
        public global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.Content.ContentRequestBuilder Content
        {
            get => new global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.Content.ContentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The media property</summary>
        public global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.Media.MediaRequestBuilder Media
        {
            get => new global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.Media.MediaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/umbraco/delivery/api/v2", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::UmbracoDeliveryClient.Generated.Umbraco.Delivery.Api.V2.V2RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V2RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/umbraco/delivery/api/v2", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
