using Umbraco.Core;
using Umbraco.Core.Models;

namespace Umbraco.Tests.Common.Builders.Extensions
{
    public static class ContentTypeBuilderExtensions
    {
        public static ContentType BuildSimpleContentType(this ContentTypeBuilder builder)
        {
            return (ContentType)builder
                .WithId(10)
                .WithAlias("textPage")
                .WithName("Text Page")
                .WithCreatorId(22)
                .WithDescription("test")
                .WithIsContainer(true)
                .WithIcon("icon")
                .WithThumbnail("thumb")
                .WithSortOrder(5)
                .WithLevel(3)
                .WithPath("-1,4,10")
                .WithPropertyTypeIdsIncrementingFrom(200)
                .AddPropertyGroup()
                    .WithName("Content")
                    .WithSortOrder(1)
                    .AddPropertyType()
                        .WithPropertyEditorAlias(Constants.PropertyEditors.Aliases.TextBox)
                        .WithValueStorageType(ValueStorageType.Nvarchar)
                        .WithAlias("title")
                        .WithName("Title")
                        .WithSortOrder(1)
                        .WithDataTypeId(-88)
                        .Done()
                    .AddPropertyType()
                        .WithPropertyEditorAlias(Constants.PropertyEditors.Aliases.TextBox)
                        .WithValueStorageType(ValueStorageType.Ntext)
                        .WithAlias("bodyText")
                        .WithName("Body text")
                        .WithSortOrder(2)
                        .WithDataTypeId(-87)
                        .Done()
                    .Done()
                .AddPropertyGroup()
                    .WithName("Meta")
                    .WithSortOrder(2)
                    .AddPropertyType()
                        .WithPropertyEditorAlias(Constants.PropertyEditors.Aliases.TextBox)
                        .WithValueStorageType(ValueStorageType.Nvarchar)
                        .WithAlias("keywords")
                        .WithName("Keywords")
                        .WithSortOrder(1)
                        .WithDataTypeId(-88)
                        .Done()
                    .AddPropertyType()
                        .WithPropertyEditorAlias(Constants.PropertyEditors.Aliases.TextBox)
                        .WithValueStorageType(ValueStorageType.Nvarchar)
                        .WithAlias("description")
                        .WithName("description")
                        .WithSortOrder(1)
                        .WithDataTypeId(-88)
                        .Done()
                    .Done()
                .AddAllowedTemplate()
                    .WithId(200)
                    .WithAlias("textPage")
                    .WithName("Text Page")
                    .Done()
                .AddAllowedTemplate()
                    .WithId(201)
                    .WithAlias("textPage2")
                    .WithName("Text Page 2")
                    .Done()
                .WithDefaultTemplateId(200)
                .AddAllowedContentType()
                    .WithId(888)
                    .WithAlias("sub")
                    .WithSortOrder(8)
                    .Done()
                .AddAllowedContentType()
                    .WithId(889)
                    .WithAlias("sub2")
                    .WithSortOrder(9)
                    .Done()
                .Build();
        }

        public static MediaType BuildImageMediaType(this MediaTypeBuilder builder)
        {
            return (MediaType)builder
                .WithId(10)
                .WithAlias(Constants.Conventions.MediaTypes.Image)
                .WithName("Image")
                .WithCreatorId(22)
                .WithDescription("test")
                .WithIcon("icon")
                .WithThumbnail("thumb")
                .WithSortOrder(5)
                .WithLevel(3)
                .WithPath("-1,4,10")
                .WithPropertyTypeIdsIncrementingFrom(200)
                .WithMediaPropertyGroup()
                .Build();
        }

        public static MemberType BuildSimpleMemberType(this MemberTypeBuilder builder)
        {
            return (MemberType)builder
                .WithId(10)
                .WithAlias("memberType")
                .WithName("Member type")
                .WithCreatorId(22)
                .WithDescription("test")
                .WithIcon("icon")
                .WithThumbnail("thumb")
                .WithSortOrder(5)
                .WithLevel(3)
                .WithPath("-1,4,10")
                .WithPropertyTypeIdsIncrementingFrom(200)
                .AddPropertyGroup()
                    .WithName("Content")
                    .AddPropertyType()
                        .WithPropertyEditorAlias(Constants.PropertyEditors.Aliases.TextBox)
                        .WithValueStorageType(ValueStorageType.Nvarchar)
                        .WithAlias("title")
                        .WithName("Title")
                        .WithSortOrder(1)
                        .WithDataTypeId(-88)
                        .Done()
                    .AddPropertyType()
                        .WithPropertyEditorAlias(Constants.PropertyEditors.Aliases.TextBox)
                        .WithValueStorageType(ValueStorageType.Ntext)
                        .WithAlias("bodyText")
                        .WithName("Body text")
                        .WithSortOrder(2)
                        .WithDataTypeId(-87)
                        .Done()
                    .Done()
                .WithMemberCanEditProperty("title", true)
                .WithMemberCanViewProperty("bodyText", true)
                .Build();
        }
    }
}
