tinyMCE.addI18n('da.advimage_dlg',{
tab_general:"Generelt",
tab_appearance:"Udseende",
tab_advanced:"Avanceret",
general:"Generelt",
title:"Titel",
preview:"Vis",
constrain_proportions:"Bibehold proportioner",
langdir:"Sprogretning",
langcode:"Sprogkode",
long_desc:"Lang beskrivelseslink",
style:"Stil",
classes:"Klasser",
ltr:"Venstre til h\u00F8jre",
rtl:"H\u00F8jre til venstre",
id:"Id",
map:"Billede map",
swap_image:"Byt billede",
alt_image:"Alternativt billede",
mouseover:"for mus-over",
mouseout:"for mus-ud",
misc:"Diverse",
example_img:"Forh\u00E5ndsvisning af billede",
missing_alt:"Er du sikker p\u00E5, at du vil forts\u00E6tte uden at inkludere en billedebeskrivelse? Uden denne er billedet m\u00E5ske ikke tilg\u00E6ngeligt for nogle brugere med handicaps, eller for dem der bruger en tekstbrowser, eller som browser internettet med billeder sl\u00E5et fra.",
dialog_title:"Inds\u00E6t/rediger billede",
src:"Billed-URL",
alt:"Billedbeskrivelse",
list:"Billedliste",
border:"Kant",
dimensions:"Dimentioner",
vspace:"Vertikal afstand",
hspace:"Horisontal afstand",
align:"Justering",
align_baseline:"Grundlinje",
align_top:"Top",
align_middle:"Midte",
align_bottom:"Bund",
align_texttop:"Teksttop",
align_textbottom:"Tekstbund",
align_left:"Venstre",
align_right:"H\u00F8jre",
image_list:"Billedliste"
});