tinyMCE.addI18n('sv.advimage_dlg',{
tab_general:"Generellt",
tab_appearance:"Utseende",
tab_advanced:"Avancerat",
general:"Generellt",
title:"Titel",
preview:"F\u00F6rhandsvisning",
constrain_proportions:"Bibeh\u00E5ll proportionerna",
langdir:"Skriftriktning",
langcode:"Spr\u00E5kkod",
long_desc:"L\u00E5ng beskrivning",
style:"Stil",
classes:"Klasser",
ltr:"V\u00E4nster till h\u00F6ger",
rtl:"H\u00F6ger till v\u00E4nster",
id:"Id",
map:"L\u00E4nkkarta",
swap_image:"Utbytningsbild",
alt_image:"Alternativbild",
mouseover:"vid musen ovanf\u00F6r",
mouseout:"vid musen utanf\u00F6r",
misc:"\u00D6\u0096vrigt",
example_img:"Exempelbild",
missing_alt:"Vill du forts\u00E4tta utan bildbeskrivning. Icke grafiska webbl\u00E4sare kommer inte kunna tolka bilden f\u00F6r anv\u00E4ndaren.",
dialog_title:"Infoga/redigera bild",
src:"Bildens URL",
alt:"Bildens beskrivning",
list:"Bildlista",
border:"Ram",
dimensions:"Dimensioner",
vspace:"Vertikalrymd",
hspace:"Horisontalrymd",
align:"Justering",
align_baseline:"Baslinje",
align_top:"Toppen",
align_middle:"Mitten",
align_bottom:"Botten",
align_texttop:"Toppen av texten",
align_textbottom:"Botten av texten",
align_left:"V\u00E4nster",
align_right:"H\u00F6ger",
image_list:"Bildlista"
});