tinyMCE.addI18n('nl.advlink_dlg',{
title:"Link invoegen/bewerken",
url:"URL",
target:"Doel",
titlefield:"Titel",
is_email:"De ingevoerde URL lijkt op een e-mailadres. Wilt u de vereiste mailto: tekst voorvoegen?",
is_external:"De ingevoerde URL lijkt op een externe link. Wilt u de vereiste http:// tekst voorvoegen?",
list:"Lijst",
general_tab:"Algemeen",
popup_tab:"Popup",
events_tab:"Gebeurtenissen",
advanced_tab:"Geavanceerd",
general_props:"Algemene eigenschappen",
popup_props:"Popup eigenschappen",
event_props:"Gebeurtenissen",
advanced_props:"Geavanceerde eigenschappen",
popup_opts:"Opties",
anchor_names:"Ankers",
target_same:"In dit venster / frame openen",
target_parent:"In bovenliggend venster / frame openen",
target_top:"In bovenste frame openen (vervangt gehele pagina)",
target_blank:"In nieuw venster openen",
popup:"Javascript popup",
popup_url:"Popup URL",
popup_name:"Venstertitel",
popup_return:"'return false' invoegen",
popup_scrollbars:"Scrollbalken weergeven",
popup_statusbar:"Statusbalk weergeven",
popup_toolbar:"Werkbalk weergeven",
popup_menubar:"Menubalk weergeven",
popup_location:"Lokatiebalk weergeven",
popup_resizable:"Aanpasbaar venster",
popup_dependent:"Afhankelijk (Alleen Mozilla/Firefox)",
popup_size:"Grootte",
popup_position:"Positie (X/Y)",
id:"Id",
style:"Stijl",
classes:"Klasses",
target_name:"Doel",
langdir:"Taalrichting",
target_langcode:"Taal",
langcode:"Taalcode",
encoding:"Taalcodering",
mime:"MIME type",
rel:"Relatie van pagina tot doel",
rev:"Relatie van doel tot pagina",
tabindex:"Tabvolgorde",
accesskey:"Toegangstoets",
ltr:"Van links naar rechts",
rtl:"Van rechts naar links",
link_list:"Lijst"
});