//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umbraco.presentation.umbraco.controls {
    
    
    public partial class TreeControl {
        
        /// <summary>
        /// ClientDependencyInclude7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude7;
        
        /// <summary>
        /// ClientDependencyInclude8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude8;
        
        /// <summary>
        /// ClientDependencyInclude13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude13;
        
        /// <summary>
        /// ClientDependencyInclude11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude11;
        
        /// <summary>
        /// ClientDependencyInclude12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude12;
        
        /// <summary>
        /// ClientDependencyInclude6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude6;
        
        /// <summary>
        /// ClientDependencyInclude1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude1;
        
        /// <summary>
        /// ClientDependencyInclude2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude2;
        
        /// <summary>
        /// ClientDependencyInclude5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude5;
        
        /// <summary>
        /// ClientDependencyInclude3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude3;
        
        /// <summary>
        /// ClientDependencyInclude4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::umbraco.presentation.ClientDependency.ClientDependencyInclude ClientDependencyInclude4;
    }
}
