// FR lang variables
// Modified by Motte, last updated 2006-03-23

tinyMCE.addToLang('',{
bold_desc : 'Gras',
italic_desc : 'Italique',
underline_desc : 'Soulign&eacute;',
striketrough_desc : 'Barr&eacute;',
justifyleft_desc : 'Aligner &agrave; gauche',
justifycenter_desc : 'Centrer',
justifyright_desc : 'Aligner &agrave; droite',
justifyfull_desc : 'Justifier',
bullist_desc : 'Liste &agrave; puces',
numlist_desc : 'Liste num&eacute;rot&eacute;e',
outdent_desc : 'Diminuer le retrait',
indent_desc : 'Augmenter le retrait',
undo_desc : 'Annuler',
redo_desc : 'Restaurer',
link_desc : 'Ins&eacute;rer/Modifier un lien',
unlink_desc : 'Supprimer le lien',
image_desc : 'Ins&eacute;rer/Modifier une image',
cleanup_desc : 'Nettoyer le code',
focus_alert : 'Une instance de l\&eacute;diteur doit avoir le focus avant d\'utiliser cette commande.',
edit_confirm : 'Voulez-vous utiliser le mode WYSIWYG pour cette zone d\'&eacute;dition de texte ?',
insert_link_title : 'Gestionnaire d\'hyperlien',
insert : 'Ins&eacute;rer',
update : 'Appliquer',
cancel : 'Annuler',
insert_link_url : 'Lien URL',
insert_link_target : 'Cible',
insert_link_target_same : 'Ouvrir dans la m&ecirc;me fen&ecirc;tre',
insert_link_target_blank : 'Ouvrir dans une nouvelle fen&ecirc;tre',
insert_image_title : 'Gestionnaire d\'image',
insert_image_src : 'URL de l\'image',
insert_image_alt : 'Equivalent textuel',
help_desc : 'Aide',
bold_img : "bold_fr.gif",
italic_img : "italic.gif",
underline_img : "underline_fr.gif",
clipboard_msg : 'Pour des raisons de s&eacute;curit&eacute;, les fonctions « Copier », « Couper » et « Coller »\nne sont pas disponibles dans Mozilla et Firefox.\n\n\nVoulez-vous plus d\'information &agrave; ce sujet?\n',
popup_blocked : 'D&eacute;sol&eacute;, mais votre bloqueur de pop-up emp&ecirc;che le fonctionnement normal de l\'application.\n\n\nPour utiliser cet outil, veuillez r&eacute;gler votre navigateur pour qu\'il accepte les pop-up de ce site.'
});
