// JA lang variables

tinyMCE.addToLang('',{
bold_desc : '太字 (Ctrl+B)',
italic_desc : '斜体 (Ctrl+I)',
underline_desc : '下線 (Ctrl+U)',
striketrough_desc : '打ち消し線',
justifyleft_desc : '左揃え',
justifycenter_desc : '中央揃え',
justifyright_desc : '右揃え',
justifyfull_desc : '均等割り付け',
bullist_desc : '箇条書き',
numlist_desc : '段落番号',
outdent_desc : 'インデント解除',
indent_desc : 'インデント',
undo_desc : '元に戻す (Ctrl+Z)',
redo_desc : 'やり直し (Ctrl+Y)',
link_desc : 'ハイパーリンク',
unlink_desc : 'ハイパーリンクの削除',
image_desc : '画像',
cleanup_desc : 'コード整理',
focus_alert : 'このコマンドを使う前にエディタ上のどこかを選択する必要があります。',
edit_confirm : 'WYSIWYGモードでこのテキストエリアを編集しますか？',
insert_link_title : 'ハイパーリンク',
insert : '挿入',
update : '更新',
cancel : 'キャンセル',
insert_link_url : 'ＵＲＬ',
insert_link_target : 'ターゲット',
insert_link_target_same : '同じウィンドウで開く',
insert_link_target_blank : '新しいウィンドウで開く',
insert_image_title : '画像の登録',
insert_image_src : 'ＵＲＬ',
insert_image_alt : '画像の説明',
help_desc : 'ヘルプ',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'コピー/切り取り/貼り付けはMozillaまたはFirefoxでは使用できません\nこの警告に関する詳細情報を表示しますか？',
popup_blocked : 'ポップアップブロックが有効になっているためエディタの機能が一部制約されています\nこのツールを使用する場合はこのサイトに対するポップアップブロックを無効にしてください。'
});
