// SE lang variables

tinyMCE.addToLang('',{
bold_desc : 'Fet',
italic_desc : 'Kursiv',
underline_desc : 'Understruken',
striketrough_desc : 'Genomstruken',
justifyleft_desc : 'Vänsterjustera',
justifycenter_desc : 'Centrera',
justifyright_desc : 'Högerjustera',
justifyfull_desc : 'Kantjustera',
bullist_desc : 'Punktlista',
numlist_desc : 'Nummerlista',
outdent_desc : 'Utdrag',
indent_desc : 'Indrag',
undo_desc : 'Ångra',
redo_desc : 'Gör om',
link_desc : 'Skapa länk',
unlink_desc : 'Ta bort länk',
image_desc : 'Skapa/redigera bild',
cleanup_desc : 'Rensa skräpkod',
focus_alert : 'Flytta markören till en textyta innan du använder detta kommando.',
edit_confirm : 'Vill du använda WYSIWYG-editorn för detta textfält?',
insert_link_title : 'Skapa/redigera länk',
insert : 'Skapa',
update : 'Uppdatera',
cancel : 'Avbryt',
insert_link_url : 'Länkens URL',
insert_link_target : 'Fönster',
insert_link_target_same : 'Öppna länken i samma fönster',
insert_link_target_blank : 'Öppna länken i ett nytt fönster',
insert_link_delta_width : 20,
insert_link_delta_height : 10,
insert_image_title : 'Skapa/redigera bild',
insert_image_src : 'Bildens URL',
insert_image_alt : 'Bildens beskrivning',
bold_img : 'bold_de_se.gif',
italic_img : 'italic_de_se.gif',
underline_img : "underline.gif",
clipboard_msg : 'Klipp ut/Kopiera/Klistra in fungerar inte Mozilla och Firefox. Vill du veta mer om detta?',
help_desc : "Hjälp",
popup_blocked : 'En popupblockerare har spärrat ett fönster som behövs för denna funktion. Avaktivera popupblockeraren om du vill kunna använda funktionen.'
});
