export const manifests: Array<UmbExtensionManifest> = [
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Save',
		name: 'Save Audit Log Type',
		forLogTypeAliases: ['Save'],
		meta: { look: 'primary', color: 'default', label: 'auditTrails_smallSave', desc: 'auditTrails_save' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.SaveVariant',
		name: 'Save Variant Audit Log Type',
		forLogTypeAliases: ['SaveVariant'],
		meta: { look: 'primary', color: 'default', label: 'auditTrails_smallSaveVariant', desc: 'auditTrails_savevariant' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Publish',
		name: 'Publish Audit Log Type',
		forLogTypeAliases: ['Publish'],
		meta: { look: 'primary', color: 'positive', label: 'auditTrails_smallPublish', desc: 'auditTrails_publish' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.PublishVariant',
		name: 'Publish Variant Audit Log Type',
		forLogTypeAliases: ['PublishVariant'],
		meta: { look: 'primary', color: 'positive', label: 'auditTrails_smallPublishVariant', desc: 'auditTrails_publishvariant' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Unpublish',
		name: 'Unpublish Audit Log Type',
		forLogTypeAliases: ['Unpublish'],
		meta: { look: 'primary', color: 'warning', label: 'auditTrails_smallUnpublish', desc: 'auditTrails_unpublish' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.UnpublishVariant',
		name: 'Unpublish Variant Audit Log Type',
		forLogTypeAliases: ['UnpublishVariant'],
		meta: { look: 'primary', color: 'warning', label: 'auditTrails_smallUnpublishVariant', desc: 'auditTrails_unpublishvariant' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.SendToPublish',
		name: 'Send To Publish Audit Log Type',
		forLogTypeAliases: ['SendToPublish'],
		meta: { look: 'secondary', color: 'positive', label: 'auditTrails_smallSendToPublish', desc: 'auditTrails_sendtopublish' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.SendToPublishVariant',
		name: 'Send To Publish Variant Audit Log Type',
		forLogTypeAliases: ['SendToPublishVariant'],
		meta: { look: 'secondary', color: 'positive', label: 'auditTrails_smallSendToPublishVariant', desc: 'auditTrails_sendtopublishvariant' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.RollBack',
		name: 'Roll Back Audit Log Type',
		forLogTypeAliases: ['RollBack'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallRollBack', desc: 'auditTrails_rollback' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Copy',
		name: 'Copy Audit Log Type',
		forLogTypeAliases: ['Copy'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallCopy', desc: 'auditTrails_copy' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Move',
		name: 'Move Audit Log Type',
		forLogTypeAliases: ['Move'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallMove', desc: 'auditTrails_move' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Delete',
		name: 'Delete Audit Log Type',
		forLogTypeAliases: ['Delete'],
		meta: { look: 'secondary', color: 'danger', label: 'auditTrails_smallDelete', desc: 'auditTrails_delete' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Sort',
		name: 'Sort Audit Log Type',
		forLogTypeAliases: ['Sort'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallSort', desc: 'auditTrails_sort' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.AssignDomain',
		name: 'Assign Domain Audit Log Type',
		forLogTypeAliases: ['AssignDomain'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallAssignDomain', desc: 'auditTrails_assigndomain' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.ContentVersionEnableCleanup',
		name: 'Content Version Enable Cleanup Audit Log Type',
		forLogTypeAliases: ['ContentVersionEnableCleanup'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallContentVersionEnableCleanup', desc: 'auditTrails_contentversionenablecleanup' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.ContentVersionPreventCleanup',
		name: 'Content Version Prevent Cleanup Audit Log Type',
		forLogTypeAliases: ['ContentVersionPreventCleanup'],
		meta: { look: 'secondary', color: 'default', label: 'auditTrails_smallContentVersionPreventCleanup', desc: 'auditTrails_contentversionpreventcleanup' },
	},
	{
		type: 'auditLogType',
		alias: 'Umb.AuditLogType.Custom',
		name: 'Custom Audit Log Type',
		forLogTypeAliases: ['Custom'],
		meta: { look: 'placeholder', color: 'default', label: 'auditTrails_smallCustom', desc: 'auditTrails_custom' },
	},
];
