tinyMCE.addI18n('sv.umbimage_dlg', {
    tab_general: 'Generellt',
    tab_appearance: 'Utseende',
    tab_advanced: 'Avancerat',
    general: 'Generellt',
    title: 'Titel',
    preview: 'Förhandsgranska',
    constrain_proportions: 'Bibehåll proportioner',
    langdir: 'Språkdirektion',
    langcode: 'Språkkod',
    long_desc: 'Lång länkbeskrivning',
    style: 'Stil',
    classes: 'Klasser',
    ltr: 'Vänster till höger',
    rtl: 'höger till vänster',
    id: 'Id',
    map: 'Bildkarta',
    swap_image: 'Byt bild',
    alt_image: 'Alternativ bild',
    mouseover: 'För musen över',
    mouseout: 'för musen utanför',
    misc: 'Blandat',
    example_img: 'Visning av bildförhandsgranskning',
    missing_alt: 'Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.',
    dialog_title: 'Infoga/redigera bild',
    src: 'Bild URL',
    alt: 'Bildbeskrivning',
    list: 'Bildlista',
    border: 'Ram',
    dimensions: 'Dimensioner',
    vspace: 'Vertikalt avstånd',
    hspace: 'Horisontellt avstånd',
    align: 'Position',
    align_baseline: 'Baslinje',
    align_top: 'Toppen',
    align_middle: 'Mitten',
    align_bottom: 'Botten',
    align_texttop: 'Text topp',
    align_textbottom: 'Text botten',
    align_left: 'Vänster',
    align_right: 'Höger',
    image_list: 'Bildlista'
});