tinyMCE.addI18n('ru.advlink_dlg', {
"target_name": "Открыть в окне",
classes: "Классы CSS",
style: "Стиль CSS",
id: "ID",
"popup_position": "Позиционирование (X/Y)",
langdir: "Направление письма",
"popup_size": "Размер",
"popup_dependent": "Зависимость (Только Mozilla/Firefox)",
"popup_resizable": "Изменяемый размер",
"popup_location": "Показывать поле адреса",
"popup_menubar": "Покзывать строку меню",
"popup_toolbar": "Показывать панель инструментов",
"popup_statusbar": "Показывать панель состояния",
"popup_scrollbars": "Показывать прокрутку",
"popup_return": "Вставить \'return false\'",
"popup_name": "Название окна",
"popup_url": "Ссылка на источник",
popup: "Всплывающее окно JavaScript",
"target_blank": "Открыть в новом окне",
"target_top": "Открыть в главном фрейме",
"target_parent": "Открыть в родительском окне/фрейме",
"target_same": "Открыть в том же окне/фрейме",
"anchor_names": "Якоря",
"popup_opts": "Настройки",
"advanced_props": "Дополнительные свойства",
"event_props": "События",
"popup_props": "Свойства окна",
"general_props": "Общие свойства",
"advanced_tab": "Дополнительно",
"events_tab": "События",
"popup_tab": "Окно",
"general_tab": "Общее",
list: "Список ссылок",
"is_external": "Указанная Вами ссылка по всей видимости внешняя. Добавить в ее начало префикс 'http://'?",
"is_email": "Указанная Вами ссылка выглядит как адрес email. Добавить в ее начало префикс 'mailto:'?",
titlefield: "Заголовок",
target: "Назначение",
url: "Ссылка (URL)",
title: "Вставить/изменить ссылку",
"link_list": "Список ссылок",
rtl: "Справа налево",
ltr: "Слева направо",
accesskey: "Ключ доступа",
tabindex: "Порядок обхода",
rev: "Связь 'Назначение к странице'",
rel: "Связь 'Страница к назначению'",
mime: "MIME-тип назначения",
encoding: "Кодовая таблица назначения",
langcode: "Код языка",
"target_langcode": "Язык",
width: "Ширина",
height: "Высота"
});