export const foundConsts = [{
				path: '@umbraco-cms/internal/test-utils',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/app',
				consts: ["UMB_APP_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/class-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/context-api',
				consts: ["UMB_CONTEXT_REQUEST_EVENT_TYPE","UMB_CONTENT_REQUEST_EVENT_TYPE","UMB_DEBUG_CONTEXT_EVENT_TYPE","UMB_CONTEXT_PROVIDE_EVENT_TYPE","UMB_CONTEXT_UNPROVIDED_EVENT_TYPE"]
			},
{
				path: '@umbraco-cms/backoffice/controller-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/element-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/embedded-media',
				consts: ["UMB_EMBEDDED_MEDIA_MODAL","UMB_OEMBED_REPOSITORY_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/extension-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/formatting-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/localization-api',
				consts: ["UMB_DEFAULT_LOCALIZATION_CULTURE"]
			},
{
				path: '@umbraco-cms/backoffice/observable-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/action',
				consts: ["UMB_ACTION_EVENT_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/audit-log',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/auth',
				consts: ["UMB_AUTH_CONTEXT","UMB_STORAGE_TOKEN_RESPONSE_NAME","UMB_MODAL_APP_AUTH"]
			},
{
				path: '@umbraco-cms/backoffice/block-custom-view',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/block-grid',
				consts: ["UMB_GRID_BLOCK_CLIPBOARD_ENTRY_VALUE_TYPE","UMB_BLOCK_GRID_AREA_CONFIG_ENTRY_CONTEXT","UMB_BLOCK_GRID_AREA_TYPE_WORKSPACE_CONTEXT","UMB_BLOCK_GRID_AREA_TYPE_WORKSPACE_CONTEXT","UMB_BLOCK_GRID_AREA_TYPE_WORKSPACE_MODAL","UMB_BLOCK_GRID_AREA_TYPE_WORKSPACE_ALIAS","UMB_BLOCK_GRID_TYPE","UMB_BLOCK_GRID","UMB_BLOCK_GRID_ENTRIES_CONTEXT","UMB_BLOCK_GRID_ENTRY_CONTEXT","UMB_BLOCK_GRID_MANAGER_CONTEXT","UMB_BLOCK_GRID_DEFAULT_LAYOUT_STYLESHEET","UMB_BLOCK_GRID_AREA_TYPE_ENTRIES_CONTEXT","UMB_BLOCK_GRID_PROPERTY_EDITOR_SCHEMA_ALIAS","UMB_BLOCK_GRID_PROPERTY_EDITOR_UI_ALIAS","UMB_BLOCK_GRID_TYPE_WORKSPACE_MODAL","UMB_BLOCK_GRID_WORKSPACE_MODAL","UMB_BLOCK_GRID_TYPE_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/block-list',
				consts: ["UMB_BLOCK_LIST_TYPE","UMB_BLOCK_LIST","UMB_BLOCK_LIST_ENTRIES_CONTEXT","UMB_BLOCK_LIST_ENTRY_CONTEXT","UMB_BLOCK_LIST_MANAGER_CONTEXT","UMB_BLOCK_LIST_PROPERTY_EDITOR_SCHEMA_ALIAS","UMB_BLOCK_LIST_PROPERTY_EDITOR_UI_ALIAS","UMB_BLOCK_LIST_WORKSPACE_MODAL","UMB_BLOCK_LIST_TYPE_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/block-rte',
				consts: ["UMB_BLOCK_RTE_TYPE","UMB_BLOCK_RTE","UMB_BLOCK_RTE_PROPERTY_EDITOR_SCHEMA_ALIAS","UMB_BLOCK_RTE_ENTRIES_CONTEXT","UMB_BLOCK_RTE_ENTRY_CONTEXT","UMB_BLOCK_RTE_MANAGER_CONTEXT","UMB_BLOCK_RTE_WORKSPACE_MODAL","UMB_BLOCK_RTE_TYPE_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/block-type',
				consts: ["UMB_BLOCK_TYPE_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/block',
				consts: ["UMB_BLOCK_CLIPBOARD_ENTRY_VALUE_TYPE","UMB_BLOCK_ENTRIES_CONTEXT","UMB_BLOCK_ENTRY_CONTEXT","UMB_BLOCK_MANAGER_CONTEXT","UMB_BLOCK_CATALOGUE_MODAL","UMB_BLOCK_ELEMENT_PROPERTY_DATASET_CONTEXT","UMB_BLOCK_WORKSPACE_CONTEXT","UMB_BLOCK_WORKSPACE_MODAL","UMB_BLOCK_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/clipboard',
				consts: ["UMB_CLIPBOARD_ENTRY_DETAIL_STORE_CONTEXT","UMB_CLIPBOARD_ENTRY_DETAIL_REPOSITORY_ALIAS","UMB_CLIPBOARD_ENTRY_DETAIL_STORE_ALIAS","UMB_CLIPBOARD_ENTRY_ENTITY_TYPE","UMB_CLIPBOARD_ENTRY_ITEM_STORE_CONTEXT","UMB_CLIPBOARD_ENTRY_ITEM_REPOSITORY_ALIAS","UMB_CLIPBOARD_ENTRY_ITEM_STORE_ALIAS","UMB_CLIPBOARD_ENTRY_PICKER_MODAL","UMB_CLIPBOARD_ENTRY_PICKER_MODAL_ALIAS","UMB_CLIPBOARD_ROOT_WORKSPACE_ALIAS","UMB_CLIPBOARD_ROOT_ENTITY_TYPE","UMB_CLIPBOARD_COLLECTION_ALIAS","UMB_CLIPBOARD_COLLECTION_REPOSITORY_ALIAS","UMB_CLIPBOARD_TABLE_COLLECTION_VIEW_ALIAS","UMB_CLIPBOARD_CONTEXT","UMB_CLIPBOARD_PROPERTY_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/code-editor',
				consts: ["UMB_CODE_EDITOR_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/collection',
				consts: ["UMB_COLLECTION_ALIAS_CONDITION","UMB_COLLECTION_BULK_ACTION_PERMISSION_CONDITION","UMB_COLLECTION_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/components',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/const',
				consts: ["UMB_MARK_ATTRIBUTE_NAME"]
			},
{
				path: '@umbraco-cms/backoffice/content-type',
				consts: ["UMB_COMPOSITION_PICKER_MODAL","UMB_CONTENT_TYPE_WORKSPACE_CONTEXT","UMB_PROPERTY_TYPE_CONTEXT","UMB_CONTENT_TYPE_DESIGN_EDITOR_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/content',
				consts: ["UMB_CONTENT_COLLECTION_WORKSPACE_CONTEXT","UMB_CONTENT_HAS_PROPERTIES_WORKSPACE_CONDITION","UMB_CONTENT_SECTION_ALIAS","UMB_CONTENT_PROPERTY_CONTEXT","UMB_CONTENT_PROPERTY_DATASET_CONTEXT","UMB_CONTENT_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/culture',
				consts: ["UMB_CULTURE_REPOSITORY_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/current-user',
				consts: ["UMB_CURRENT_USER_GROUP_ID_CONDITION_ALIAS","UMB_CURRENT_USER_IS_ADMIN_CONDITION_ALIAS","UMB_CURRENT_USER_CONTEXT","UMB_CURRENT_USER_EXTERNAL_LOGIN_MODAL","UMB_CURRENT_USER_HISTORY_STORE_CONTEXT","UMB_CURRENT_USER_MODAL","UMB_CURRENT_USER_MFA_MODAL","UMB_CURRENT_USER_MFA_DISABLE_PROVIDER_MODAL","UMB_CURRENT_USER_MFA_ENABLE_PROVIDER_MODAL","UMB_CURRENT_USER_REPOSITORY_ALIAS","UMB_CURRENT_USER_STORE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/dashboard',
				consts: ["UMB_DASHBOARD_PATH_PATTERN"]
			},
{
				path: '@umbraco-cms/backoffice/data-type',
				consts: ["UMB_DATA_TYPE_COLLECTION_ALIAS","UMB_DATA_TYPE_COLLECTION_REPOSITORY_ALIAS","UMB_DATA_TYPE_ROOT_WORKSPACE_ALIAS","UMB_DATA_TYPE_CREATE_OPTIONS_MODAL","UMB_DUPLICATE_DATA_TYPE_REPOSITORY_ALIAS","UMB_MOVE_DATA_TYPE_REPOSITORY_ALIAS","UMB_DATA_TYPE_ENTITY_TYPE","UMB_DATA_TYPE_ROOT_ENTITY_TYPE","UMB_DATA_TYPE_FOLDER_ENTITY_TYPE","UMB_DATA_TYPE_PICKER_FLOW_DATA_TYPE_PICKER_MODAL","UMB_DATA_TYPE_PICKER_FLOW_MODAL","UMB_DATA_TYPE_PICKER_MODAL","UMB_DATA_TYPE_WORKSPACE_PATH","UMB_DATA_TYPE_ROOT_WORKSPACE_PATH","UMB_CREATE_DATA_TYPE_WORKSPACE_PATH_PATTERN","UMB_EDIT_DATA_TYPE_WORKSPACE_PATH_PATTERN","UMB_DATA_TYPE_REFERENCE_REPOSITORY_ALIAS","UMB_DATA_TYPE_DETAIL_REPOSITORY_ALIAS","UMB_DATA_TYPE_DETAIL_STORE_ALIAS","UMB_DATA_TYPE_DETAIL_STORE_CONTEXT","UMB_DATA_TYPE_ITEM_REPOSITORY_ALIAS","UMB_DATA_TYPE_STORE_ALIAS","UMB_DATA_TYPE_ITEM_STORE_CONTEXT","UMB_DATA_TYPE_TREE_REPOSITORY_ALIAS","UMB_DATA_TYPE_TREE_STORE_ALIAS","UMB_DATA_TYPE_TREE_ALIAS","UMB_DATA_TYPE_TREE_STORE_CONTEXT","UMB_DATA_TYPE_FOLDER_REPOSITORY_ALIAS","UMB_DATA_TYPE_FOLDER_STORE_ALIAS","UMB_DATA_TYPE_FOLDER_STORE_CONTEXT","UMB_DATA_TYPE_FOLDER_WORKSPACE_ALIAS","UMB_DATA_TYPE_FOLDER_WORKSPACE_CONTEXT","UMB_DATA_TYPE_FOLDER_WORKSPACE_PATH","UMB_EDIT_DATA_TYPE_FOLDER_WORKSPACE_PATH_PATTERN","UMB_DATA_TYPE_TREE_ITEM_CHILDREN_COLLECTION_ALIAS","UMB_DATA_TYPE_TREE_ITEM_CHILDREN_COLLECTION_REPOSITORY_ALIAS","UMB_DATA_TYPE_WORKSPACE_ALIAS","UMB_DATA_TYPE_WORKSPACE_CONTEXT","UMB_DATATYPE_WORKSPACE_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/debug',
				consts: ["UMB_CONTEXT_DEBUGGER_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/dictionary',
				consts: ["UMB_DICTIONARY_COLLECTION_ALIAS","UMB_DICTIONARY_COLLECTION_REPOSITORY_ALIAS","UMB_DICTIONARY_TABLE_COLLECTION_VIEW_ALIAS","UMB_DICTIONARY_OVERVIEW_DASHBOARD_PATHNAME","UMB_DICTIONARY_OVERVIEW_DASHBOARD_PATH","UMB_EXPORT_DICTIONARY_MODAL","UMB_IMPORT_DICTIONARY_MODAL","UMB_MOVE_DICTIONARY_REPOSITORY_ALIAS","UMB_DICTIONARY_ROOT_ENTITY_TYPE","UMB_DICTIONARY_ENTITY_TYPE","UMB_DICTIONARY_PICKER_MODAL","UMB_DICTIONARY_DETAIL_REPOSITORY_ALIAS","UMB_DICTIONARY_DETAIL_STORE_ALIAS","UMB_DICTIONARY_DETAIL_STORE_CONTEXT","UMB_DICTIONARY_EXPORT_REPOSITORY_ALIAS","UMB_DICTIONARY_IMPORT_REPOSITORY_ALIAS","UMB_DICTIONARY_ITEM_REPOSITORY_ALIAS","UMB_DICTIONARY_STORE_ALIAS","UMB_DICTIONARY_ITEM_STORE_CONTEXT","UMB_DICTIONARY_SEARCH_PROVIDER_ALIAS","UMB_DICTIONARY_TREE_REPOSITORY_ALIAS","UMB_DICTIONARY_TREE_STORE_ALIAS","UMB_DICTIONARY_TREE_ALIAS","UMB_DICTIONARY_TREE_STORE_CONTEXT","UMB_DICTIONARY_WORKSPACE_ALIAS","UMB_DICTIONARY_WORKSPACE_CONTEXT","UMB_DICTIONARY_WORKSPACE_PATH","UMB_CREATE_DICTIONARY_WORKSPACE_PATH_PATTERN","UMB_EDIT_DICTIONARY_WORKSPACE_PATH_PATTERN"]
			},
{
				path: '@umbraco-cms/backoffice/document-blueprint',
				consts: ["UMB_DOCUMENT_BLUEPRINT_OPTIONS_CREATE_MODAL","UMB_MOVE_DOCUMENT_BLUEPRINT_REPOSITORY_ALIAS","UMB_DOCUMENT_BLUEPRINT_ROOT_ENTITY_TYPE","UMB_DOCUMENT_BLUEPRINT_ENTITY_TYPE","UMB_DOCUMENT_BLUEPRINT_FOLDER_ENTITY_TYPE","UMB_DOCUMENT_BLUEPRINT_WORKSPACE_PATH","UMB_CREATE_DOCUMENT_BLUEPRINT_WORKSPACE_PATH_PATTERN","UMB_EDIT_BLUEPRINT_DOCUMENT_WORKSPACE_PATH_PATTERN","UMB_DOCUMENT_BLUEPRINT_PROPERTY_DATASET_CONTEXT","UMB_DOCUMENT_BLUEPRINT_DETAIL_REPOSITORY_ALIAS","UMB_DOCUMENT_BLUEPRINT_DETAIL_STORE_ALIAS","UMB_DOCUMENT_BLUEPRINT_DETAIL_STORE_CONTEXT","UMB_DOCUMENT_BLUEPRINT_ITEM_REPOSITORY_ALIAS","UMB_DOCUMENT_BLUEPRINT_STORE_ALIAS","UMB_DOCUMENT_BLUEPRINT_ITEM_STORE_CONTEXT","UMB_DOCUMENT_BLUEPRINT_TREE_REPOSITORY_ALIAS","UMB_DOCUMENT_BLUEPRINT_TREE_STORE_ALIAS","UMB_DOCUMENT_BLUEPRINT_TREE_ALIAS","UMB_DOCUMENT_BLUEPRINT_TREE_STORE_CONTEXT","UMB_DOCUMENT_BLUEPRINT_FOLDER_REPOSITORY_ALIAS","UMB_DOCUMENT_BLUEPRINT_FOLDER_STORE_ALIAS","UMB_DOCUMENT_BLUEPRINT_FOLDER_STORE_CONTEXT","UMB_DOCUMENT_BLUEPRINT_FOLDER_WORKSPACE_ALIAS","UMB_DOCUMENT_BLUEPRINT_FOLDER_WORKSPACE_CONTEXT","UMB_DOCUMENT_BLUEPRINT_WORKSPACE_ALIAS","UMB_DOCUMENT_BLUEPRINT_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/document-type',
				consts: ["UMB_DOCUMENT_TYPE_CREATE_OPTIONS_MODAL","UMB_DUPLICATE_DOCUMENT_TYPE_REPOSITORY_ALIAS","UMB_EXPORT_DOCUMENT_TYPE_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_IMPORT_MODAL","UMB_DOCUMENT_TYPE_IMPORT_REPOSITORY_ALIAS","UMB_MOVE_DOCUMENT_TYPE_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_ENTITY_TYPE","UMB_DOCUMENT_TYPE_ROOT_ENTITY_TYPE","UMB_DOCUMENT_TYPE_PICKER_MODAL","UMB_CREATE_DOCUMENT_TYPE_WORKSPACE_PRESET_TEMPLATE","UMB_CREATE_DOCUMENT_TYPE_WORKSPACE_PRESET_ELEMENT","UMB_DOCUMENT_TYPE_WORKSPACE_PATH","UMB_CREATE_DOCUMENT_TYPE_WORKSPACE_PATH_PATTERN","UMB_EDIT_DOCUMENT_TYPE_WORKSPACE_PATH_PATTERN","UMB_DOCUMENT_TYPE_COMPOSITION_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_DETAIL_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_DETAIL_STORE_ALIAS","UMB_DOCUMENT_TYPE_DETAIL_STORE_CONTEXT","UMB_DOCUMENT_TYPE_ITEM_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_ITEM_STORE_ALIAS","UMB_DOCUMENT_TYPE_ITEM_STORE_CONTEXT","UMB_DOCUMENT_TYPE_STRUCTURE_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_SEARCH_PROVIDER_ALIAS","UMB_DOCUMENT_TYPE_TREE_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_TREE_STORE_ALIAS","UMB_DOCUMENT_TYPE_TREE_ALIAS","UMB_DOCUMENT_TYPE_TREE_STORE_CONTEXT","UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE","UMB_DOCUMENT_TYPE_FOLDER_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_FOLDER_STORE_ALIAS","UMB_DOCUMENT_TYPE_FOLDER_STORE_CONTEXT","UMB_DOCUMENT_TYPE_FOLDER_WORKSPACE_ALIAS","UMB_DOCUMENT_TYPE_FOLDER_WORKSPACE_CONTEXT","UMB_DOCUMENT_TYPE_FOLDER_WORKSPACE_PATH","UMB_EDIT_DOCUMENT_TYPE_FOLDER_WORKSPACE_PATH_PATTERN","UMB_DOCUMENT_TYPE_TREE_ITEM_CHILDREN_COLLECTION_ALIAS","UMB_DOCUMENT_TYPE_TREE_ITEM_CHILDREN_COLLECTION_REPOSITORY_ALIAS","UMB_DOCUMENT_TYPE_WORKSPACE_ALIAS","UMB_DOCUMENT_TYPE_WORKSPACE_CONTEXT","UMB_DOCUMENT_TYPE_WORKSPACE_MODAL","UMB_DOCUMENT_TYPE_ROOT_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/document',
				consts: ["UMB_DOCUMENT_COLLECTION_ALIAS","UMB_DOCUMENT_COLLECTION_CONTEXT","UMB_DOCUMENT_COLLECTION_REPOSITORY_ALIAS","UMB_DOCUMENT_GRID_COLLECTION_VIEW_ALIAS","UMB_DOCUMENT_TABLE_COLLECTION_VIEW_ALIAS","UMB_DOCUMENT_CREATE_OPTIONS_MODAL","UMB_CREATE_BLUEPRINT_MODAL","UMB_DOCUMENT_CREATE_BLUEPRINT_REPOSITORY_ALIAS","UMB_CULTURE_AND_HOSTNAMES_MODAL","UMB_DOCUMENT_CULTURE_AND_HOSTNAMES_REPOSITORY_ALIAS","UMB_DUPLICATE_DOCUMENT_MODAL","UMB_DUPLICATE_DOCUMENT_MODAL_ALIAS","UMB_DUPLICATE_DOCUMENT_REPOSITORY_ALIAS","UMB_MOVE_DOCUMENT_REPOSITORY_ALIAS","UMB_DOCUMENT_NOTIFICATIONS_MODAL","UMB_DOCUMENT_NOTIFICATIONS_MODAL_ALIAS","UMB_DOCUMENT_NOTIFICATIONS_REPOSITORY_ALIAS","UMB_PUBLIC_ACCESS_MODAL","UMB_DOCUMENT_PUBLIC_ACCESS_REPOSITORY_ALIAS","UMB_SORT_CHILDREN_OF_DOCUMENT_REPOSITORY_ALIAS","UMB_BULK_DUPLICATE_DOCUMENT_REPOSITORY_ALIAS","UMB_BULK_MOVE_DOCUMENT_REPOSITORY_ALIAS","UMB_BULK_TRASH_DOCUMENT_REPOSITORY_ALIAS","UMB_DOCUMENT_ENTITY_TYPE","UMB_DOCUMENT_ROOT_ENTITY_TYPE","UMB_DOCUMENT_CONFIGURATION_CONTEXT","UMB_CONTENT_MENU_ALIAS","UMB_DOCUMENT_PICKER_MODAL","UMB_DOCUMENT_SAVE_MODAL","UMB_DOCUMENT_SAVE_MODAL_ALIAS","UMB_DOCUMENT_WORKSPACE_PATH","UMB_CREATE_FROM_BLUEPRINT_DOCUMENT_WORKSPACE_PATH_PATTERN","UMB_CREATE_DOCUMENT_WORKSPACE_PATH_PATTERN","UMB_EDIT_DOCUMENT_WORKSPACE_PATH_PATTERN","UMB_DOCUMENT_PROPERTY_DATASET_CONTEXT","UMB_DOCUMENT_PUBLISH_MODAL_ALIAS","UMB_DOCUMENT_PUBLISH_MODAL","UMB_DOCUMENT_PUBLISH_WITH_DESCENDANTS_MODAL_ALIAS","UMB_DOCUMENT_PUBLISH_WITH_DESCENDANTS_MODAL","UMB_DOCUMENT_PUBLISHING_REPOSITORY_ALIAS","UMB_DOCUMENT_SCHEDULE_MODAL_ALIAS","UMB_DOCUMENT_SCHEDULE_MODAL","UMB_DOCUMENT_UNPUBLISH_MODAL_ALIAS","UMB_DOCUMENT_UNPUBLISH_MODAL","UMB_DOCUMENT_PUBLISHING_WORKSPACE_CONTEXT","UMB_DOCUMENT_RECYCLE_BIN_ROOT_ENTITY_TYPE","UMB_DOCUMENT_RECYCLE_BIN_REPOSITORY_ALIAS","UMB_DOCUMENT_RECYCLE_BIN_TREE_REPOSITORY_ALIAS","UMB_DOCUMENT_RECYCLE_BIN_TREE_STORE_ALIAS","UMB_DOCUMENT_RECYCLE_BIN_TREE_ALIAS","UMB_DOCUMENT_RECYCLE_BIN_TREE_STORE_CONTEXT","UMB_DOCUMENT_REFERENCE_REPOSITORY_ALIAS","UMB_DOCUMENT_DETAIL_REPOSITORY_ALIAS","UMB_DOCUMENT_DETAIL_STORE_ALIAS","UMB_DOCUMENT_DETAIL_STORE_CONTEXT","UMB_DOCUMENT_ITEM_REPOSITORY_ALIAS","UMB_DOCUMENT_STORE_ALIAS","UMB_DOCUMENT_ITEM_STORE_CONTEXT","UMB_DOCUMENT_VALIDATION_REPOSITORY_ALIAS","UMB_ROLLBACK_MODAL_ALIAS","UMB_ROLLBACK_MODAL","UMB_ROLLBACK_REPOSITORY_ALIAS","UMB_DOCUMENT_SEARCH_PROVIDER_ALIAS","UMB_DOCUMENT_TREE_STORE_CONTEXT","UMB_DOCUMENT_TREE_REPOSITORY_ALIAS","UMB_DOCUMENT_TREE_STORE_ALIAS","UMB_DOCUMENT_TREE_ALIAS","UMB_DOCUMENT_URL_REPOSITORY_ALIAS","UMB_DOCUMENT_URL_STORE_ALIAS","UMB_DOCUMENT_URL_STORE_CONTEXT","UMB_DOCUMENT_USER_PERMISSION_CONDITION_ALIAS","UMB_USER_PERMISSION_DOCUMENT_CREATE","UMB_USER_PERMISSION_DOCUMENT_READ","UMB_USER_PERMISSION_DOCUMENT_UPDATE","UMB_USER_PERMISSION_DOCUMENT_DELETE","UMB_USER_PERMISSION_DOCUMENT_CREATE_BLUEPRINT","UMB_USER_PERMISSION_DOCUMENT_NOTIFICATIONS","UMB_USER_PERMISSION_DOCUMENT_PUBLISH","UMB_USER_PERMISSION_DOCUMENT_PERMISSIONS","UMB_USER_PERMISSION_DOCUMENT_UNPUBLISH","UMB_USER_PERMISSION_DOCUMENT_DUPLICATE","UMB_USER_PERMISSION_DOCUMENT_MOVE","UMB_USER_PERMISSION_DOCUMENT_SORT","UMB_USER_PERMISSION_DOCUMENT_CULTURE_AND_HOSTNAMES","UMB_USER_PERMISSION_DOCUMENT_PUBLIC_ACCESS","UMB_USER_PERMISSION_DOCUMENT_ROLLBACK","UMB_DOCUMENT_PERMISSION_REPOSITORY_ALIAS","UMB_DOCUMENT_IS_NOT_TRASHED_CONDITION_ALIAS","UMB_DOCUMENT_IS_TRASHED_CONDITION_ALIAS","UMB_DOCUMENT_WORKSPACE_ALIAS","UMB_DOCUMENT_DETAIL_MODEL_VARIANT_SCAFFOLD","UMB_DOCUMENT_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/entity-action',
				consts: ["UMB_ENTITY_CREATE_OPTION_ACTION_LIST_MODAL_ALIAS","UMB_ENTITY_CREATE_OPTION_ACTION_LIST_MODAL","UMB_ENTITY_ACTION_DEFAULT_KIND_MANIFEST"]
			},
{
				path: '@umbraco-cms/backoffice/entity-bulk-action',
				consts: ["UMB_ENTITY_BULK_ACTION_DEFAULT_KIND_MANIFEST"]
			},
{
				path: '@umbraco-cms/backoffice/entity-create-option-action',
				consts: ["UMB_EXTENSION_TYPE_ENTITY_CREATE_OPTION_ACTION"]
			},
{
				path: '@umbraco-cms/backoffice/entity',
				consts: ["UMB_ENTITY_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/event',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/extension-registry',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/health-check',
				consts: ["UMB_HEALTHCHECK_DASHBOARD_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/help',
				consts: ["UMB_HELP_MENU_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/icon',
				consts: ["UMB_ICON_PICKER_MODAL","UMB_ICON_REGISTRY_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/id',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/imaging',
				consts: ["UMB_IMAGING_REPOSITORY_ALIAS","UMB_IMAGING_STORE_ALIAS","UMB_IMAGING_STORE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/language',
				consts: ["UMB_LANGUAGE_COLLECTION_ALIAS","UMB_LANGUAGE_COLLECTION_REPOSITORY_ALIAS","UMB_LANGUAGE_TABLE_COLLECTION_VIEW_ALIAS","UMB_LANGUAGE_ENTITY_TYPE","UMB_LANGUAGE_ROOT_ENTITY_TYPE","UMB_APP_LANGUAGE_CONTEXT","UMB_LANGUAGE_PICKER_MODAL","UMB_LANGUAGE_WORKSPACE_PATH","UMB_CREATE_LANGUAGE_WORKSPACE_PATH_PATTERN","UMB_EDIT_LANGUAGE_WORKSPACE_PATH_PATTERN","UMB_LANGUAGE_ACCESS_WORKSPACE_CONTEXT","UMB_LANGUAGE_DETAIL_REPOSITORY_ALIAS","UMB_LANGUAGE_DETAIL_STORE_ALIAS","UMB_LANGUAGE_DETAIL_STORE_CONTEXT","UMB_LANGUAGE_ITEM_REPOSITORY_ALIAS","UMB_LANGUAGE_STORE_ALIAS","UMB_LANGUAGE_ITEM_STORE_CONTEXT","UMB_LANGUAGE_WORKSPACE_ALIAS","UMB_LANGUAGE_WORKSPACE_CONTEXT","UMB_LANGUAGE_WORKSPACE_MODAL","UMB_LANGUAGE_ROOT_WORKSPACE_ALIAS","UMB_LANGUAGE_ROOT_WORKSPACE_PATH"]
			},
{
				path: '@umbraco-cms/backoffice/lit-element',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/localization',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/log-viewer',
				consts: ["UMB_APP_LOG_VIEWER_CONTEXT","UMB_LOG_VIEWER_SAVE_SEARCH_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/markdown-editor',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/media-type',
				consts: ["UMB_MEDIA_TYPE_CREATE_OPTIONS_MODAL","UMB_DUPLICATE_MEDIA_TYPE_REPOSITORY_ALIAS","UMB_EXPORT_MEDIA_TYPE_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_IMPORT_MODAL","UMB_MEDIA_TYPE_IMPORT_REPOSITORY_ALIAS","UMB_MOVE_MEDIA_TYPE_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_ENTITY_TYPE","UMB_MEDIA_TYPE_ROOT_ENTITY_TYPE","UMB_MEDIA_TYPE_FOLDER_ENTITY_TYPE","UMB_MEDIA_TYPE_ROOT_WORKSPACE_ALIAS","UMB_MEDIA_TYPE_WORKSPACE_PATH","UMB_MEDIA_TYPE_ROOT_WORKSPACE_PATH","UMB_CREATE_MEDIA_TYPE_WORKSPACE_PATH_PATTERN","UMB_EDIT_MEDIA_TYPE_WORKSPACE_PATH_PATTERN","UMB_MEDIA_TYPE_COMPOSITION_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_DETAIL_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_DETAIL_STORE_ALIAS","UMB_MEDIA_TYPE_DETAIL_STORE_CONTEXT","UMB_MEDIA_TYPE_ITEM_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_ITEM_STORE_ALIAS","UMB_MEDIA_TYPE_ITEM_STORE_CONTEXT","UMB_MEDIA_TYPE_STRUCTURE_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_TREE_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_TREE_STORE_ALIAS","UMB_MEDIA_TYPE_TREE_ALIAS","UMB_MEDIA_TYPE_FOLDER_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_FOLDER_STORE_ALIAS","UMB_MEDIA_TYPE_FOLDER_STORE_CONTEXT","UMB_MEDIA_TYPE_FOLDER_WORKSPACE_ALIAS","UMB_MEDIA_TYPE_FOLDER_WORKSPACE_CONTEXT","UMB_MEDIA_TYPE_FOLDER_WORKSPACE_PATH","UMB_EDIT_MEDIA_TYPE_FOLDER_WORKSPACE_PATH_PATTERN","UMB_MEDIA_TYPE_PICKER_MODAL","UMB_MEDIA_TYPE_TREE_STORE_CONTEXT","UMB_MEDIA_TYPE_TREE_ITEM_CHILDREN_COLLECTION_ALIAS","UMB_MEDIA_TYPE_TREE_ITEM_CHILDREN_COLLECTION_REPOSITORY_ALIAS","UMB_MEDIA_TYPE_WORKSPACE_ALIAS","UMB_MEDIA_TYPE_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/media',
				consts: ["UMB_MEDIA_COLLECTION_ALIAS","UMB_MEDIA_COLLECTION_CONTEXT","UMB_MEDIA_COLLECTION_REPOSITORY_ALIAS","UMB_MEDIA_GRID_COLLECTION_VIEW_ALIAS","UMB_MEDIA_TABLE_COLLECTION_VIEW_ALIAS","UMB_DROPZONE_MEDIA_TYPE_PICKER_MODAL","UMB_MEDIA_CREATE_OPTIONS_MODAL","UMB_MOVE_MEDIA_REPOSITORY_ALIAS","UMB_SORT_CHILDREN_OF_MEDIA_REPOSITORY_ALIAS","UMB_BULK_MOVE_MEDIA_REPOSITORY_ALIAS","UMB_BULK_TRASH_MEDIA_REPOSITORY_ALIAS","UMB_MEDIA_ENTITY_TYPE","UMB_MEDIA_ROOT_ENTITY_TYPE","UMB_MEDIA_PLACEHOLDER_ENTITY_TYPE","UMB_MEDIA_MENU_ALIAS","UMB_IMAGE_CROPPER_EDITOR_MODAL","UMB_MEDIA_CAPTION_ALT_TEXT_MODAL","UMB_MEDIA_PICKER_MODAL","UMB_MEDIA_WORKSPACE_PATH","UMB_CREATE_MEDIA_WORKSPACE_PATH_PATTERN","UMB_EDIT_MEDIA_WORKSPACE_PATH_PATTERN","UMB_MEDIA_VARIANT_CONTEXT","UMB_MEDIA_RECYCLE_BIN_ROOT_ENTITY_TYPE","UMB_MEDIA_RECYCLE_BIN_REPOSITORY_ALIAS","UMB_MEDIA_RECYCLE_BIN_TREE_REPOSITORY_ALIAS","UMB_MEDIA_RECYCLE_BIN_TREE_STORE_ALIAS","UMB_MEDIA_RECYCLE_BIN_TREE_ALIAS","UMB_MEDIA_RECYCLE_BIN_TREE_STORE_CONTEXT","UMB_MEDIA_REFERENCE_REPOSITORY_ALIAS","UMB_MEDIA_DETAIL_REPOSITORY_ALIAS","UMB_MEDIA_DETAIL_STORE_ALIAS","UMB_MEDIA_DETAIL_STORE_CONTEXT","UMB_MEDIA_ITEM_REPOSITORY_ALIAS","UMB_MEDIA_STORE_ALIAS","UMB_MEDIA_ITEM_STORE_CONTEXT","UMB_MEDIA_VALIDATION_REPOSITORY_ALIAS","UMB_MEDIA_SEARCH_PROVIDER_ALIAS","UMB_MEDIA_TREE_REPOSITORY_ALIAS","UMB_MEDIA_TREE_STORE_ALIAS","UMB_MEDIA_TREE_ALIAS","UMB_MEDIA_TREE_PICKER_MODAL","UMB_MEDIA_TREE_STORE_CONTEXT","UMB_MEDIA_URL_REPOSITORY_ALIAS","UMB_MEDIA_URL_STORE_ALIAS","UMB_MEDIA_URL_STORE_CONTEXT","UMB_MEDIA_WORKSPACE_ALIAS","UMB_MEMBER_DETAIL_MODEL_VARIANT_SCAFFOLD","UMB_MEDIA_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/member-group',
				consts: ["UMB_MEMBER_GROUP_COLLECTION_ALIAS","UMB_MEMBER_GROUP_COLLECTION_REPOSITORY_ALIAS","UMB_MEMBER_GROUP_TABLE_COLLECTION_VIEW_ALIAS","UMB_MEMBER_GROUP_PICKER_MODAL","UMB_MEMBER_GROUP_ROOT_ENTITY_TYPE","UMB_MEMBER_GROUP_ENTITY_TYPE","UMB_MEMBER_GROUP_WORKSPACE_PATH","UMB_MEMBER_GROUP_ROOT_WORKSPACE_PATH","UMB_MEMBER_GROUP_DETAIL_REPOSITORY_ALIAS","UMB_MEMBER_GROUP_DETAIL_STORE_ALIAS","UMB_MEMBER_GROUP_DETAIL_STORE_CONTEXT","UMB_MEMBER_GROUP_ITEM_REPOSITORY_ALIAS","UMB_MEMBER_GROUP_STORE_ALIAS","UMB_MEMBER_GROUP_ITEM_STORE_CONTEXT","UMB_MEMBER_GROUP_WORKSPACE_ALIAS","UMB_MEMBER_GROUP_WORKSPACE_CONTEXT","UMB_MEMBER_GROUP_ROOT_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/member-type',
				consts: ["UMB_DUPLICATE_MEMBER_TYPE_REPOSITORY_ALIAS","UMB_MEMBER_TYPE_ROOT_ENTITY_TYPE","UMB_MEMBER_TYPE_ENTITY_TYPE","UMB_MEMBER_TYPE_PICKER_MODAL","UMB_MEMBER_TYPE_COMPOSITION_REPOSITORY_ALIAS","UMB_MEMBER_TYPE_DETAIL_REPOSITORY_ALIAS","UMB_MEMBER_TYPE_DETAIL_STORE_ALIAS","UMB_MEMBER_TYPE_DETAIL_STORE_CONTEXT","UMB_MEMBER_TYPE_ITEM_REPOSITORY_ALIAS","UMB_MEMBER_TYPE_STORE_ALIAS","UMB_MEMBER_TYPE_ITEM_STORE_CONTEXT","UMB_MEMBER_TYPE_TREE_REPOSITORY_ALIAS","UMB_MEMBER_TYPE_TREE_STORE_ALIAS","UMB_MEMBER_TYPE_TREE_ALIAS","UMB_MEMBER_TYPE_TREE_STORE_CONTEXT","UMB_MEMBER_TYPE_WORKSPACE_ALIAS","UMB_MEMBER_TYPE_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/member',
				consts: ["UMB_MEMBER_COLLECTION_ALIAS","UMB_MEMBER_COLLECTION_CONTEXT","UMB_MEMBER_COLLECTION_REPOSITORY_ALIAS","UMB_MEMBER_TABLE_COLLECTION_VIEW_ALIAS","UMB_MEMBER_PICKER_MODAL","UMB_MEMBER_CREATE_OPTIONS_MODAL","UMB_MEMBER_ENTITY_TYPE","UMB_MEMBER_ROOT_ENTITY_TYPE","UMB_MEMBER_WORKSPACE_PATH","UMB_MEMBER_ROOT_WORKSPACE_PATH","UMB_CREATE_MEMBER_WORKSPACE_PATH_PATTERN","UMB_MEMBER_VARIANT_CONTEXT","UMB_MEMBER_DETAIL_REPOSITORY_ALIAS","UMB_MEMBER_DETAIL_STORE_ALIAS","UMB_MEMBER_DETAIL_STORE_CONTEXT","UMB_MEMBER_ITEM_REPOSITORY_ALIAS","UMB_MEMBER_STORE_ALIAS","UMB_MEMBER_ITEM_STORE_CONTEXT","UMB_MEMBER_VALIDATION_REPOSITORY_ALIAS","UMB_MEMBER_SEARCH_PROVIDER_ALIAS","UMB_MEMBER_DETAIL_MODEL_VARIANT_SCAFFOLD","UMB_MEMBER_WORKSPACE_ALIAS","UMB_MEMBER_WORKSPACE_CONTEXT","UMB_MEMBER_ROOT_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/menu',
				consts: ["UMB_MENU_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/modal',
				consts: ["UMB_CONFIRM_MODAL","UMB_DISCARD_CHANGES_MODAL","UMB_ITEM_PICKER_MODAL","UMB_MODAL_MANAGER_CONTEXT","UMB_MODAL_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/models',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/multi-url-picker',
				consts: ["UMB_MULTI_URL_PICKER_MODAL_ALIAS","UMB_LINK_PICKER_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/notification',
				consts: ["UMB_NOTIFICATION_HEADER","UMB_NOTIFICATION_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/object-type',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/package',
				consts: ["UMB_PACKAGE_REPOSITORY_ALIAS","UMB_PACKAGE_STORE_ALIAS","UMB_PACKAGE_STORE_TOKEN"]
			},
{
				path: '@umbraco-cms/backoffice/partial-view',
				consts: ["UMB_PARTIAL_VIEW_CREATE_OPTIONS_MODAL","UMB_PARTIAL_VIEW_FROM_SNIPPET_MODAL","UMB_RENAME_PARTIAL_VIEW_REPOSITORY_ALIAS","UMB_RENAME_PARTIAL_VIEW_ENTITY_ACTION_ALIAS","UMB_PARTIAL_VIEW_ENTITY_TYPE","UMB_PARTIAL_VIEW_ROOT_ENTITY_TYPE","UMB_PARTIAL_VIEW_FOLDER_ENTITY_TYPE","UMB_PARTIAL_VIEW_PICKER_MODAL","UMB_PARTIAL_VIEW_ITEM_REPOSITORY_ALIAS","UMB_PARTIAL_VIEW_ITEM_STORE_ALIAS","UMB_PARTIAL_VIEW_ITEM_STORE_CONTEXT","UMB_PARTIAL_VIEW_DETAIL_REPOSITORY_ALIAS","UMB_PARTIAL_VIEW_DETAIL_STORE_ALIAS","UMB_PARTIAL_VIEW_DETAIL_STORE_CONTEXT","UMB_DELETE_PARTIAL_VIEW_FOLDER_ENTITY_ACTION_ALIAS","UMB_PARTIAL_VIEW_FOLDER_REPOSITORY_ALIAS","UMB_PARTIAL_VIEW_FOLDER_STORE_ALIAS","UMB_PARTIAL_VIEW_FOLDER_STORE_CONTEXT","UMB_PARTIAL_VIEW_FOLDER_WORKSPACE_ALIAS","UMB_PARTIAL_VIEW_FOLDER_WORKSPACE_CONTEXT","UMB_PARTIAL_VIEW_TREE_REPOSITORY_ALIAS","UMB_PARTIAL_VIEW_TREE_STORE_ALIAS","UMB_PARTIAL_VIEW_TREE_ALIAS","UMB_PARTIAL_VIEW_TREE_STORE_CONTEXT","UMB_PARTIAL_VIEW_WORKSPACE_ALIAS","UMB_PARTIAL_VIEW_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/picker-input',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/picker',
				consts: ["UMB_PICKER_CONTEXT","UMB_PICKER_SEARCH_RESULT_ITEM_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/property-action',
				consts: ["UMB_PROPERTY_ACTION_DEFAULT_KIND_MANIFEST"]
			},
{
				path: '@umbraco-cms/backoffice/property-editor',
				consts: ["UMB_PROPERTY_EDITOR_SCHEMA_ALIAS_DEFAULT","UMB_PROPERTY_EDITOR_UI_PICKER_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/property-type',
				consts: ["UMB_PROPERTY_TYPE_WORKSPACE_ALIAS","UMB_PROPERTY_TYPE_ENTITY_TYPE","UMB_PROPERTY_TYPE_WORKSPACE_PATH","UMB_CREATE_PROPERTY_TYPE_WORKSPACE_PATH_PATTERN","UMB_EDIT_PROPERTY_TYPE_WORKSPACE_PATH_PATTERN","UMB_PROPERTY_TYPE_WORKSPACE_CONTEXT","UMB_PROPERTY_TYPE_WORKSPACE_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/property',
				consts: ["UMB_PROPERTY_CONTEXT","UMB_UNSUPPORTED_EDITOR_SCHEMA_ALIASES","UMB_PROPERTY_HAS_VALUE_CONDITION_ALIAS","UMB_WRITABLE_PROPERTY_CONDITION_ALIAS","UMB_NAMEABLE_PROPERTY_DATASET_CONTEXT","UMB_PROPERTY_DATASET_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/recycle-bin',
				consts: ["UMB_ENTITY_IS_NOT_TRASHED_CONDITION_ALIAS","UMB_ENTITY_IS_TRASHED_CONDITION_ALIAS","UMB_IS_TRASHED_ENTITY_CONTEXT","UMB_RESTORE_FROM_RECYCLE_BIN_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/relation-type',
				consts: ["UMB_RELATION_TYPE_COLLECTION_ALIAS","UMB_RELATION_TYPE_COLLECTION_REPOSITORY_ALIAS","UMB_RELATION_TYPE_ROOT_ENTITY_TYPE","UMB_RELATION_TYPE_ENTITY_TYPE","UMB_RELATION_TYPE_DETAIL_REPOSITORY_ALIAS","UMB_RELATION_TYPE_DETAIL_STORE_ALIAS","UMB_RELATION_TYPE_DETAIL_STORE_CONTEXT","UMB_RELATION_TYPE_WORKSPACE_ALIAS","UMB_RELATION_TYPE_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/relations',
				consts: ["UMB_RELATION_COLLECTION_REPOSITORY_ALIAS","UMB_RELATION_ENTITY_TYPE"]
			},
{
				path: '@umbraco-cms/backoffice/repository',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/resources',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/router',
				consts: ["UMB_ROUTE_CONTEXT","UMB_ROUTE_PATH_ADDENDUM_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/rte',
				consts: ["UMB_BLOCK_RTE_PROPERTY_EDITOR_SCHEMA_ALIAS","UMB_BLOCK_RTE_DATA_CONTENT_KEY"]
			},
{
				path: '@umbraco-cms/backoffice/script',
				consts: ["UMB_SCRIPT_CREATE_OPTIONS_MODAL","UMB_DELETE_SCRIPT_ENTITY_ACTION_ALIAS","UMB_RENAME_SCRIPT_REPOSITORY_ALIAS","UMB_RENAME_SCRIPT_ENTITY_ACTION_ALIAS","UMB_SCRIPT_ENTITY_TYPE","UMB_SCRIPT_ROOT_ENTITY_TYPE","UMB_SCRIPT_FOLDER_ENTITY_TYPE","UMB_SCRIPT_MENU_ITEM_ALIAS","UMB_SCRIPT_PICKER_MODAL","UMB_SCRIPT_DETAIL_REPOSITORY_ALIAS","UMB_SCRIPT_DETAIL_STORE_ALIAS","UMB_SCRIPT_ITEM_REPOSITORY_ALIAS","UMB_SCRIPT_ITEM_STORE_ALIAS","UMB_SCRIPT_ITEM_STORE_CONTEXT","UMB_SCRIPT_DETAIL_STORE_CONTEXT","UMB_DELETE_SCRIPT_FOLDER_ENTITY_ACTION_ALIAS","UMB_SCRIPT_FOLDER_REPOSITORY_ALIAS","UMB_SCRIPT_FOLDER_STORE_ALIAS","UMB_SCRIPT_FOLDER_STORE_CONTEXT","UMB_SCRIPT_FOLDER_WORKSPACE_ALIAS","UMB_SCRIPT_FOLDER_WORKSPACE_CONTEXT","UMB_SCRIPT_TREE_REPOSITORY_ALIAS","UMB_SCRIPT_TREE_STORE_ALIAS","UMB_SCRIPT_TREE_ALIAS","UMB_SCRIPT_TREE_STORE_CONTEXT","UMB_SCRIPT_WORKSPACE_ALIAS","UMB_SAVE_SCRIPT_WORKSPACE_ACTION_ALIAS","UMB_SCRIPT_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/search',
				consts: ["UMB_EXAMINE_FIELDS_SETTINGS_MODAL","UMB_EXAMINE_FIELDS_VIEWER_MODAL","UMB_SEARCH_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/section',
				consts: ["UMB_SECTION_USER_PERMISSION_CONDITION_ALIAS","UMB_SECTION_PATH_PATTERN","UMB_SECTION_ITEM_REPOSITORY_ALIAS","UMB_SECTION_PICKER_MODAL","UMB_SECTION_SIDEBAR_CONTEXT","UMB_SECTION_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/server-file-system',
				consts: ["UMB_RENAME_SERVER_FILE_MODAL_ALIAS","UMB_RENAME_SERVER_FILE_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/settings',
				consts: ["UMB_ADVANCED_SETTINGS_MENU_ALIAS","UMB_SETTINGS_SECTION_ALIAS","UMB_SETTINGS_SECTION_PATHNAME","UMB_SETTINGS_SECTION_PATH","UMB_STRUCTURE_SETTINGS_MENU_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/sorter',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/static-file',
				consts: ["UMB_STATIC_FILE_PICKER_MODAL","UMB_STATIC_FILE_ITEM_REPOSITORY_ALIAS","UMB_STATIC_FILE_STORE_ALIAS","UMB_STATIC_FILE_ITEM_STORE_CONTEXT","UMB_STATIC_FILE_ITEM_STORE_CONTEXT","UMB_STATIC_FILE_TREE_REPOSITORY_ALIAS","UMB_STATIC_FILE_TREE_STORE_ALIAS","UMB_STATIC_FILE_TREE_ALIAS","UMB_STATIC_FILE_TREE_ITEM_ALIAS","UMB_STATIC_FILE_ENTITY_TYPE","UMB_STATIC_FILE_ROOT_ENTITY_TYPE","UMB_STATIC_FILE_FOLDER_ENTITY_TYPE","UMB_STATIC_FILE_TREE_STORE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/store',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/style',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/stylesheet',
				consts: ["UMB_STYLESHEET_CREATE_OPTIONS_MODAL","UMB_RENAME_STYLESHEET_REPOSITORY_ALIAS","UMB_RENAME_STYLESHEET_ENTITY_ACTION_ALIAS","UMB_STYLESHEET_ENTITY_TYPE","UMB_STYLESHEET_ROOT_ENTITY_TYPE","UMB_STYLESHEET_FOLDER_ENTITY_TYPE","UMB_STYLESHEET_PICKER_MODAL","UMB_STYLESHEET_RULE_SETTINGS_MODAL_ALIAS","UMB_STYLESHEET_RULE_SETTINGS_MODAL","UMB_STYLESHEET_ITEM_REPOSITORY_ALIAS","UMB_STYLESHEET_ITEM_STORE_ALIAS","UMB_STYLESHEET_ITEM_STORE_CONTEXT","UMB_STYLESHEET_DETAIL_REPOSITORY_ALIAS","UMB_STYLESHEET_DETAIL_STORE_ALIAS","UMB_STYLESHEET_DETAIL_STORE_CONTEXT","UMB_DELETE_STYLESHEET_FOLDER_ENTITY_ACTION_ALIAS","UMB_STYLESHEET_FOLDER_REPOSITORY_ALIAS","UMB_STYLESHEET_FOLDER_STORE_ALIAS","UMB_STYLESHEET_FOLDER_STORE_CONTEXT","UMB_STYLESHEET_FOLDER_WORKSPACE_ALIAS","UMB_STYLESHEET_FOLDER_WORKSPACE_CONTEXT","UMB_STYLESHEET_TREE_ALIAS","UMB_STYLESHEET_TREE_REPOSITORY_ALIAS","UMB_STYLESHEET_TREE_STORE_ALIAS","UMB_STYLESHEET_TREE_STORE_CONTEXT","UMB_STYLESHEET_WORKSPACE_ALIAS","UMB_STYLESHEET_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/sysinfo',
				consts: ["UMB_NEWVERSION_MODAL","UMB_SYSINFO_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/tags',
				consts: ["UMB_TAG_REPOSITORY_ALIAS","UMB_TAG_STORE_ALIAS","UMB_TAG_STORE_CONTEXT_ALIAS","UMB_TAG_STORE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/template',
				consts: ["UMB_TEMPLATE_ALLOW_DELETE_ACTION_CONDITION_ALIAS","UMB_TEMPLATE_ROOT_ENTITY_TYPE","UMB_TEMPLATE_ENTITY_TYPE","UMB_TEMPLATE_QUERY_BUILDER_MODAL","UMB_TEMPLATE_PICKER_MODAL","UMB_TEMPLATE_DETAIL_REPOSITORY_ALIAS","UMB_TEMPLATE_DETAIL_STORE_ALIAS","UMB_TEMPLATE_DETAIL_STORE_CONTEXT","UMB_TEMPLATE_ITEM_REPOSITORY_ALIAS","UMB_TEMPLATE_STORE_ALIAS","UMB_TEMPLATE_ITEM_STORE_CONTEXT","UMB_TEMPLATE_QUERY_REPOSITORY_ALIAS","UMB_TEMPLATE_TREE_REPOSITORY_ALIAS","UMB_TEMPLATE_TREE_STORE_ALIAS","UMB_TEMPLATE_TREE_ALIAS","UMB_TEMPLATE_TREE_STORE_CONTEXT","UMB_TEMPLATE_WORKSPACE_ALIAS","UMB_TEMPLATE_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/temporary-file',
				consts: ["UMB_TEMPORARY_FILE_CONFIG_STORE_CONTEXT","UMB_TEMPORARY_FILE_REPOSITORY_ALIAS","UMB_TEMPORARY_FILE_CONFIG_STORE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/themes',
				consts: ["UMB_THEME_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/tiny-mce',
				consts: ["UMB_BLOCK_ENTRY_WEB_COMPONENTS_ABSOLUTE_PATH","UMB_BLOCK_ENTRY_WEB_COMPONENTS_ABSOLUTE_PATH","UMB_BLOCK_RTE_PROPERTY_EDITOR_UI_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/tiptap',
				consts: ["UMB_TIPTAP_TOOLBAR_CONFIGURATION_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/translation',
				consts: ["UMB_TRANSLATION_MENU_ALIAS","UMB_TRANSLATION_SECTION_ALIAS","UMB_TRANSLATION_SECTION_PATHNAME","UMB_TRANSLATION_SECTION_PATH"]
			},
{
				path: '@umbraco-cms/backoffice/tree',
				consts: ["UMB_TREE_CONTEXT","UMB_DUPLICATE_TO_MODAL_ALIAS","UMB_DUPLICATE_TO_MODAL","UMB_SORT_CHILDREN_OF_MODAL_ALIAS","UMB_SORT_CHILDREN_OF_MODAL","UMB_FOLDER_CREATE_MODAL","UMB_FOLDER_UPDATE_MODAL","UMB_TREE_ITEM_CONTEXT","UMB_TREE_PICKER_MODAL_ALIAS","UMB_TREE_PICKER_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/ufm',
				consts: ["UMB_UFM_RENDER_CONTEXT","UMB_UFM_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/user-change-password',
				consts: ["UMB_CHANGE_PASSWORD_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/user-group',
				consts: ["UMB_USER_GROUP_COLLECTION_ALIAS","UMB_USER_GROUP_COLLECTION_REPOSITORY_ALIAS","UMB_USER_GROUP_COLLECTION_CONTEXT","UMB_USER_GROUP_TABLE_COLLECTION_VIEW_ALIAS","UMB_USER_GROUP_ENTITY_TYPE","UMB_USER_GROUP_ROOT_ENTITY_TYPE","UMB_USER_GROUP_PICKER_MODAL","UMB_USER_GROUP_WORKSPACE_PATH","UMB_USER_GROUP_ROOT_WORKSPACE_PATH","UMB_USER_GROUP_DETAIL_REPOSITORY_ALIAS","UMB_USER_GROUP_DETAIL_STORE_ALIAS","UMB_USER_GROUP_DETAIL_STORE_CONTEXT","UMB_USER_GROUP_ITEM_REPOSITORY_ALIAS","UMB_USER_GROUP_STORE_ALIAS","UMB_USER_GROUP_ITEM_STORE_CONTEXT","UMB_USER_GROUP_WORKSPACE_ALIAS","UMB_USER_GROUP_WORKSPACE_CONTEXT","UMB_USER_GROUP_ROOT_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/user-permission',
				consts: ["UMB_ENTITY_USER_PERMISSION_MODAL"]
			},
{
				path: '@umbraco-cms/backoffice/user',
				consts: ["UMB_CREATE_USER_CLIENT_CREDENTIAL_MODAL","UMB_CREATE_USER_CLIENT_CREDENTIAL_MODAL_ALIAS","UMB_USER_CLIENT_CREDENTIAL_REPOSITORY_ALIAS","UMB_USER_COLLECTION_ALIAS","UMB_USER_COLLECTION_REPOSITORY_ALIAS","UMB_USER_COLLECTION_CONTEXT","UMB_COLLECTION_VIEW_USER_TABLE","UMB_COLLECTION_VIEW_USER_GRID","UMB_USER_ALLOW_CHANGE_PASSWORD_CONDITION_ALIAS","UMB_CURRENT_USER_ALLOW_CHANGE_PASSWORD_CONDITION_ALIAS","UMB_USER_ALLOW_DELETE_CONDITION_ALIAS","UMB_USER_ALLOW_DISABLE_CONDITION_ALIAS","UMB_USER_ALLOW_ENABLE_CONDITION_ALIAS","UMB_USER_ALLOW_EXTERNAL_LOGIN_CONDITION_ALIAS","UMB_USER_ALLOW_MFA_CONDITION_ALIAS","UMB_CURRENT_USER_ALLOW_MFA_CONDITION_ALIAS","UMB_USER_ALLOW_UNLOCK_CONDITION_ALIAS","UMB_USER_IS_DEFAULT_KIND_CONDITION_ALIAS","UMB_CREATE_USER_MODAL","UMB_CREATE_USER_SUCCESS_MODAL","UMB_CREATE_USER_MODAL_ALIAS","UMB_USER_ENTITY_TYPE","UMB_USER_ROOT_ENTITY_TYPE","UMB_INVITE_USER_MODAL","UMB_RESEND_INVITE_TO_USER_MODAL","UMB_INVITE_USER_REPOSITORY_ALIAS","UMB_USER_MFA_MODAL","UMB_USER_PICKER_MODAL","UMB_USER_WORKSPACE_PATH","UMB_USER_ROOT_WORKSPACE_PATH","UMB_USER_AVATAR_REPOSITORY_ALIAS","UMB_CHANGE_USER_PASSWORD_REPOSITORY_ALIAS","UMB_USER_CONFIG_REPOSITORY_ALIAS","UMB_USER_CONFIG_STORE_ALIAS","UMB_CURRENT_USER_CONFIG_REPOSITORY_ALIAS","UMB_CURRENT_USER_CONFIG_STORE_ALIAS","UMB_CURRENT_USER_CONFIG_STORE_CONTEXT","UMB_USER_CONFIG_STORE_CONTEXT","UMB_USER_DETAIL_REPOSITORY_ALIAS","UMB_USER_DETAIL_STORE_ALIAS","UMB_USER_DETAIL_STORE_CONTEXT","UMB_DISABLE_USER_REPOSITORY_ALIAS","UMB_ENABLE_USER_REPOSITORY_ALIAS","UMB_USER_ITEM_REPOSITORY_ALIAS","UMB_USER_ITEM_STORE_ALIAS","UMB_USER_ITEM_STORE_CONTEXT","UMB_NEW_USER_PASSWORD_REPOSITORY_ALIAS","UMB_UNLOCK_USER_REPOSITORY_ALIAS","UMB_USER_WORKSPACE_ALIAS","UMB_USER_WORKSPACE_CONTEXT","UMB_USER_ROOT_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/utils',
				consts: ["UMB_STORAGE_REDIRECT_URL"]
			},
{
				path: '@umbraco-cms/backoffice/validation',
				consts: ["UMB_VALIDATION_EMPTY_LOCALIZATION_KEY","UMB_SERVER_MODEL_VALIDATOR_CONTEXT","UMB_VALIDATION_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/variant',
				consts: ["UMB_INVARIANT_CULTURE"]
			},
{
				path: '@umbraco-cms/backoffice/webhook',
				consts: ["UMB_WEBHOOK_WORKSPACE_ALIAS","UMB_WEBHOOK_WORKSPACE","UMB_WEBHOOK_ENTITY_TYPE","UMB_WEBHOOK_ROOT_ENTITY_TYPE","UMB_WEBHOOK_DELIVERY_ENTITY_TYPE","UMB_WEBHOOK_COLLECTION_ALIAS","UMB_WEBHOOK_COLLECTION_REPOSITORY_ALIAS","UMB_WEBHOOK_TABLE_COLLECTION_VIEW_ALIAS","UMB_WEBHOOK_DETAIL_REPOSITORY_ALIAS","UMB_WEBHOOK_DETAIL_STORE_ALIAS","UMB_WEBHOOK_DETAIL_STORE_CONTEXT","UMB_WEBHOOK_ITEM_REPOSITORY_ALIAS","UMB_WEBHOOK_STORE_ALIAS","UMB_WEBHOOK_ITEM_STORE_CONTEXT","UMB_WEBHOOK_WORKSPACE_CONTEXT","UMB_WEBHOOK_DELIVERY_COLLECTION_ALIAS","UMB_WEBHOOK_DELIVERY_COLLECTION_REPOSITORY_ALIAS","UMB_WEBHOOK_EVENTS_MODAL","UMB_WEBHOOK_EVENT_REPOSITORY_ALIAS","UMB_WEBHOOK_EVENT_STORE_ALIAS","UMB_WEBHOOK_EVENT_STORE_CONTEXT","UMB_WEBHOOK_ROOT_WORKSPACE_ALIAS"]
			},
{
				path: '@umbraco-cms/backoffice/workspace',
				consts: ["UMB_WORKSPACE_SPLIT_VIEW_CONTEXT","UMB_WORKSPACE_HAS_COLLECTION_CONDITION_ALIAS","UMB_WORKSPACE_HAS_COLLECTION_CONDITION","UMB_WORKSPACE_ENTITY_IS_NEW_CONDITION_ALIAS","UMB_WORKSPACE_ENTITY_IS_NEW_CONDITION","UMB_WORKSPACE_CONDITION_ALIAS","UMB_ENTITY_WORKSPACE_CONTEXT","UMB_PROPERTY_STRUCTURE_WORKSPACE_CONTEXT","UMB_PUBLISHABLE_WORKSPACE_CONTEXT","UMB_ROUTABLE_WORKSPACE_CONTEXT","UMB_SUBMITTABLE_WORKSPACE_CONTEXT","UMB_VARIANT_WORKSPACE_CONTEXT","UMB_ENTITY_DETAIL_WORKSPACE_CONTEXT","UMB_ENTITY_NAMED_DETAIL_WORKSPACE_CONTEXT","UMB_WORKSPACE_MODAL","UMB_NAMABLE_WORKSPACE_CONTEXT","UMB_WORKSPACE_PATH_PATTERN","UMB_WORKSPACE_VIEW_PATH_PATTERN","UMB_WORKSPACE_CONTEXT"]
			},
{
				path: '@umbraco-cms/backoffice/external/backend-api',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/base64-js',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/diff',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/dompurify',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/lit',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/marked',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/monaco-editor',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/openid',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/router-slot',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/rxjs',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/tinymce',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/tiptap',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/uui',
				consts: []
			},
{
				path: '@umbraco-cms/backoffice/external/uuid',
				consts: []
			}];