# Choose base docker image to use
# https://github.com/devcontainers/images/tree/main/src/dotnet
# https://mcr.microsoft.com/v2/devcontainers/dotnet/tags/list
FROM mcr.microsoft.com/devcontainers/dotnet:1-9.0

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1
