#!/bin/bash
set -e

# Generate HTTPS dev certificate for local Kestrel TLS.
# In Codespaces, port forwarding handles TLS for the browser, but the cert is still
# needed for the .NET runtime to bind the HTTPS endpoint without errors.
dotnet dev-certs https --trust 2>/dev/null || true

if [ -n "$CODESPACE_NAME" ]; then
    DOMAIN="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
    FRONTEND_URL="https://${CODESPACE_NAME}-5173.${DOMAIN}"
    # Port 11000 is the HTTP Kestrel endpoint. The Codespaces forwarding proxy talks plain
    # HTTP to container ports (TLS terminates at the *.app.github.dev edge), so we must
    # point external URLs at the HTTP port — not the HTTPS port 44339.
    BACKEND_URL="https://${CODESPACE_NAME}-11000.${DOMAIN}"
else
    FRONTEND_URL="http://localhost:5173"
    BACKEND_URL="https://localhost:44339"
fi

# Point Vite at the correct backend URL for this environment.
# .env.local is gitignored and takes precedence over .env.
cat > src/Umbraco.Web.UI.Client/.env.local << EOF
# Auto-generated by .devcontainer/postCreate.sh — delete to revert to .env defaults.
VITE_UMBRACO_USE_MSW=off
VITE_UMBRACO_API_URL=${BACKEND_URL}
EOF

# Write appsettings.Development.json with environment-specific URLs.
# BackOfficeHost and UmbracoApplicationUrl are NOT set as env vars in launch.json because
# env vars beat appsettings in .NET's config precedence, which would break Codespaces.
# Instead they live here so both Codespaces and local devcontainer get the right values.
cat > src/Umbraco.Web.UI/appsettings.Development.json << EOF
{
  "\$schema": "./appsettings-schema.json",
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Examine.Lucene.Providers.LuceneIndex": "Debug",
        "Examine.BaseIndexProvider": "Debug",
        "Examine.Lucene.LoggingReplicationClient": "Debug",
        "Examine.Lucene.ExamineReplicator": "Debug"
      }
    },
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console"
            }
          ]
        }
      }
    ]
  },
  "Umbraco": {
    "CMS": {
      "Examine": {
        "LuceneDirectoryFactory": "TempFileSystemDirectoryFactory"
      },
      "Hosting": {
        "Debug": true
      },
      "Security": {
        "BackOfficeHost": "${FRONTEND_URL}",
        "AuthorizeCallbackPathName": "/oauth_complete",
        "AuthorizeCallbackLogoutPathName": "/logout",
        "AuthorizeCallbackErrorPathName": "/error",
        "KeepUserLoggedIn": true,
        "BackOfficeTokenCookie": {
          "SameSite": "None"
        }
      },
      "WebRouting": {
        "UmbracoApplicationUrl": "${BACKEND_URL}"
      }
    }
  }
}
EOF

if [ -n "$CODESPACE_NAME" ]; then
    echo ""
    echo "GitHub Codespaces environment configured:"
    echo "  Frontend (Vite): ${FRONTEND_URL}"
    echo "  Backend (.NET):  ${BACKEND_URL}"
    echo "  SMTP4Dev UI:     https://${CODESPACE_NAME}-5050.${DOMAIN}"
    echo ""
else
    echo "Local devcontainer — configured with localhost URLs."
fi

echo "Setup complete. Press F5 and select 'Backoffice Launch (Vite + .NET Core)' to start debugging."
