tinyMCE.addI18n('sv.fullpage_dlg',{
title:"Dokumentinst\u00E4llningar",
meta_tab:"Generella",
appearance_tab:"Utseende",
advanced_tab:"Avancerat",
meta_props:"Metainformation",
langprops:"Spr\u00E5k och kodning",
meta_title:"Titel",
meta_keywords:"Nyckelord",
meta_description:"Bekrivning",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Spr\u00E5kkod",
langdir:"Skriftriktning",
ltr:"V\u00E4nster till h\u00F6ger",
rtl:"H\u00F6ger till v\u00E4nster",
xml_pi:"XML deklaration",
encoding:"Teckenkodning",
appearance_bgprops:"Bakgrundsinst\u00E4llningar",
appearance_marginprops:"Body marginaler",
appearance_linkprops:"L\u00E4nkf\u00E4rger",
appearance_textprops:"Textinst\u00E4llningar",
bgcolor:"Bakgrundsf\u00E4rg",
bgimage:"Bakgrundsbild",
left_margin:"V\u00E4nstermarginal",
right_margin:"H\u00F6germarginal",
top_margin:"Toppmarginal",
bottom_margin:"Bottenmarginal",
text_color:"Textf\u00E4rg",
font_size:"Textstorlek",
font_face:"Textstil",
link_color:"L\u00E4nkf\u00E4rg",
hover_color:"Hover f\u00E4rg",
visited_color:"Visited f\u00E4rg",
active_color:"Active f\u00E4rg",
textcolor:"F\u00E4rg",
fontsize:"Textstorlek",
fontface:"Textstil",
meta_index_follow:"Indexera och f\u00F6lj l\u00E4nkar",
meta_index_nofollow:"Indexera men f\u00F6lj ej l\u00E4nkar",
meta_noindex_follow:"Indexera inte men f\u00F6lj l\u00E4nkar",
meta_noindex_nofollow:"Indexera inte och f\u00F6lj ej l\u00E4nkar",
appearance_style:"Stilmall och stilegenskaper",
stylesheet:"Stilmall",
style:"Stil",
author:"F\u00F6rfattare",
copyright:"Copyright",
add:"L\u00E4gg till element",
remove:"Radera det markerade elementet",
moveup:"Flytta det markerade elementet upp\u00E5t",
movedown:"Flytta det markerade elementet ned\u00E5t",
head_elements:"Head element",
info:"Information",
add_title:"Titel-element",
add_meta:"Meta-element",
add_script:"Script-element",
add_style:"Stil-element",
add_link:"L\u00E4nk-element",
add_base:"Base-element",
add_comment:"Kommentarsnod",
title_element:"Titel-element",
script_element:"Script-element",
style_element:"Style-element",
base_element:"Base-element",
link_element:"Link-element",
meta_element:"Meta-element",
comment_element:"Comment-element",
src:"Src",
language:"Spr\u00E5k",
href:"Href",
target:"M\u00E5l",
type:"Typ",
charset:"Teckenupps\u00E4ttning",
defer:"Defer",
media:"Media",
properties:"Egenskaper",
name:"Name",
value:"Value",
content:"Inneh\u00E5ll",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Generellt",
advanced_props:"Avancerat"
});