/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum TypeAttributesModel {
    NOT_PUBLIC = 'NotPublic',
    AUTO_LAYOUT = 'AutoLayout',
    ANSI_CLASS = 'AnsiClass',
    CLASS = 'Class',
    PUBLIC = 'Public',
    NESTED_PUBLIC = 'NestedPublic',
    NESTED_PRIVATE = 'NestedPrivate',
    NESTED_FAMILY = 'NestedFamily',
    NESTED_ASSEMBLY = 'NestedAssembly',
    NESTED_FAM_ANDASSEM = 'NestedFamANDAssem',
    NESTED_FAM_ORASSEM = 'NestedFamORAssem',
    VISIBILITY_MASK = 'VisibilityMask',
    SEQUENTIAL_LAYOUT = 'SequentialLayout',
    EXPLICIT_LAYOUT = 'ExplicitLayout',
    LAYOUT_MASK = 'LayoutMask',
    INTERFACE = 'Interface',
    CLASS_SEMANTICS_MASK = 'ClassSemanticsMask',
    ABSTRACT = 'Abstract',
    SEALED = 'Sealed',
    SPECIAL_NAME = 'SpecialName',
    RTSPECIAL_NAME = 'RTSpecialName',
    IMPORT = 'Import',
    SERIALIZABLE = 'Serializable',
    WINDOWS_RUNTIME = 'WindowsRuntime',
    UNICODE_CLASS = 'UnicodeClass',
    AUTO_CLASS = 'AutoClass',
    CUSTOM_FORMAT_CLASS = 'CustomFormatClass',
    STRING_FORMAT_MASK = 'StringFormatMask',
    HAS_SECURITY = 'HasSecurity',
    RESERVED_MASK = 'ReservedMask',
    BEFORE_FIELD_INIT = 'BeforeFieldInit',
    CUSTOM_FORMAT_MASK = 'CustomFormatMask',
}
