/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { AssemblyModel } from './AssemblyModel';
import type { ConstructorInfoModel } from './ConstructorInfoModel';
import type { CustomAttributeDataModel } from './CustomAttributeDataModel';
import type { GenericParameterAttributesModel } from './GenericParameterAttributesModel';
import type { MemberTypesModel } from './MemberTypesModel';
import type { MethodBaseModel } from './MethodBaseModel';
import type { ModuleModel } from './ModuleModel';
import type { RuntimeTypeHandleModel } from './RuntimeTypeHandleModel';
import type { StructLayoutAttributeModel } from './StructLayoutAttributeModel';
import type { TypeAttributesModel } from './TypeAttributesModel';

export type TypeModel = {
    readonly name?: string;
    readonly customAttributes?: Array<CustomAttributeDataModel>;
    readonly isCollectible?: boolean;
    readonly metadataToken?: number;
    readonly isInterface?: boolean;
    memberType?: MemberTypesModel;
    readonly namespace?: string | null;
    readonly assemblyQualifiedName?: string | null;
    readonly fullName?: string | null;
    assembly?: AssemblyModel;
    module?: ModuleModel;
    readonly isNested?: boolean;
    declaringType?: TypeModel;
    declaringMethod?: MethodBaseModel;
    reflectedType?: TypeModel;
    underlyingSystemType?: TypeModel;
    readonly isTypeDefinition?: boolean;
    readonly isArray?: boolean;
    readonly isByRef?: boolean;
    readonly isPointer?: boolean;
    readonly isConstructedGenericType?: boolean;
    readonly isGenericParameter?: boolean;
    readonly isGenericTypeParameter?: boolean;
    readonly isGenericMethodParameter?: boolean;
    readonly isGenericType?: boolean;
    readonly isGenericTypeDefinition?: boolean;
    readonly isSZArray?: boolean;
    readonly isVariableBoundArray?: boolean;
    readonly isByRefLike?: boolean;
    readonly hasElementType?: boolean;
    readonly genericTypeArguments?: Array<TypeModel>;
    readonly genericParameterPosition?: number;
    genericParameterAttributes?: GenericParameterAttributesModel;
    attributes?: TypeAttributesModel;
    readonly isAbstract?: boolean;
    readonly isImport?: boolean;
    readonly isSealed?: boolean;
    readonly isSpecialName?: boolean;
    readonly isClass?: boolean;
    readonly isNestedAssembly?: boolean;
    readonly isNestedFamANDAssem?: boolean;
    readonly isNestedFamily?: boolean;
    readonly isNestedFamORAssem?: boolean;
    readonly isNestedPrivate?: boolean;
    readonly isNestedPublic?: boolean;
    readonly isNotPublic?: boolean;
    readonly isPublic?: boolean;
    readonly isAutoLayout?: boolean;
    readonly isExplicitLayout?: boolean;
    readonly isLayoutSequential?: boolean;
    readonly isAnsiClass?: boolean;
    readonly isAutoClass?: boolean;
    readonly isUnicodeClass?: boolean;
    readonly isCOMObject?: boolean;
    readonly isContextful?: boolean;
    readonly isEnum?: boolean;
    readonly isMarshalByRef?: boolean;
    readonly isPrimitive?: boolean;
    readonly isValueType?: boolean;
    readonly isSignatureType?: boolean;
    readonly isSecurityCritical?: boolean;
    readonly isSecuritySafeCritical?: boolean;
    readonly isSecurityTransparent?: boolean;
    structLayoutAttribute?: StructLayoutAttributeModel;
    typeInitializer?: ConstructorInfoModel;
    typeHandle?: RuntimeTypeHandleModel;
    readonly guid?: string;
    baseType?: TypeModel;
    readonly isSerializable?: boolean;
    readonly containsGenericParameters?: boolean;
    readonly isVisible?: boolean;
};
