// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UmbracoDeliveryClient.Generated.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::UmbracoDeliveryClient.Generated.Models.FileMediaWithCropsResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.FolderMediaWithCropsResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.ImageMediaWithCropsResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaArticleMediaWithCropsResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaAudioMediaWithCropsResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVideoMediaWithCropsResponseModel"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IApiMediaWithCropsResponseModel : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.FileMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.FileMediaWithCropsResponseModel? FileMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.FileMediaWithCropsResponseModel FileMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.FolderMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.FolderMediaWithCropsResponseModel? FolderMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.FolderMediaWithCropsResponseModel FolderMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.ImageMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.ImageMediaWithCropsResponseModel? ImageMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.ImageMediaWithCropsResponseModel ImageMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaArticleMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaArticleMediaWithCropsResponseModel? UmbracoMediaArticleMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaArticleMediaWithCropsResponseModel UmbracoMediaArticleMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaAudioMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaAudioMediaWithCropsResponseModel? UmbracoMediaAudioMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaAudioMediaWithCropsResponseModel UmbracoMediaAudioMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel? UmbracoMediaVectorGraphicsMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel UmbracoMediaVectorGraphicsMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVideoMediaWithCropsResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVideoMediaWithCropsResponseModel? UmbracoMediaVideoMediaWithCropsResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVideoMediaWithCropsResponseModel UmbracoMediaVideoMediaWithCropsResponseModel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UmbracoDeliveryClient.Generated.Models.IApiMediaWithCropsResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UmbracoDeliveryClient.Generated.Models.IApiMediaWithCropsResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("mediaType")?.GetStringValue();
            var result = new global::UmbracoDeliveryClient.Generated.Models.IApiMediaWithCropsResponseModel();
            if("File".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FileMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.FileMediaWithCropsResponseModel();
            }
            else if("Folder".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FolderMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.FolderMediaWithCropsResponseModel();
            }
            else if("Image".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ImageMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.ImageMediaWithCropsResponseModel();
            }
            else if("umbracoMediaArticle".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UmbracoMediaArticleMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaArticleMediaWithCropsResponseModel();
            }
            else if("umbracoMediaAudio".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UmbracoMediaAudioMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaAudioMediaWithCropsResponseModel();
            }
            else if("umbracoMediaVectorGraphics".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel();
            }
            else if("umbracoMediaVideo".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UmbracoMediaVideoMediaWithCropsResponseModel = new global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVideoMediaWithCropsResponseModel();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FileMediaWithCropsResponseModel != null)
            {
                return FileMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            else if(FolderMediaWithCropsResponseModel != null)
            {
                return FolderMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            else if(ImageMediaWithCropsResponseModel != null)
            {
                return ImageMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            else if(UmbracoMediaArticleMediaWithCropsResponseModel != null)
            {
                return UmbracoMediaArticleMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            else if(UmbracoMediaAudioMediaWithCropsResponseModel != null)
            {
                return UmbracoMediaAudioMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            else if(UmbracoMediaVectorGraphicsMediaWithCropsResponseModel != null)
            {
                return UmbracoMediaVectorGraphicsMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            else if(UmbracoMediaVideoMediaWithCropsResponseModel != null)
            {
                return UmbracoMediaVideoMediaWithCropsResponseModel.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(FileMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.FileMediaWithCropsResponseModel>(null, FileMediaWithCropsResponseModel);
            }
            else if(FolderMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.FolderMediaWithCropsResponseModel>(null, FolderMediaWithCropsResponseModel);
            }
            else if(ImageMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.ImageMediaWithCropsResponseModel>(null, ImageMediaWithCropsResponseModel);
            }
            else if(UmbracoMediaArticleMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaArticleMediaWithCropsResponseModel>(null, UmbracoMediaArticleMediaWithCropsResponseModel);
            }
            else if(UmbracoMediaAudioMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaAudioMediaWithCropsResponseModel>(null, UmbracoMediaAudioMediaWithCropsResponseModel);
            }
            else if(UmbracoMediaVectorGraphicsMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVectorGraphicsMediaWithCropsResponseModel>(null, UmbracoMediaVectorGraphicsMediaWithCropsResponseModel);
            }
            else if(UmbracoMediaVideoMediaWithCropsResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.UmbracoMediaVideoMediaWithCropsResponseModel>(null, UmbracoMediaVideoMediaWithCropsResponseModel);
            }
        }
    }
}
#pragma warning restore CS0618
