// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace UmbracoDeliveryClient.Generated.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::UmbracoDeliveryClient.Generated.Models.TestPageContentResponseModel"/>, <see cref="global::UmbracoDeliveryClient.Generated.Models.TestPageInvariantContentResponseModel"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IApiContentResponseModel : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.TestPageContentResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.TestPageContentResponseModel? TestPageContentResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.TestPageContentResponseModel TestPageContentResponseModel { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::UmbracoDeliveryClient.Generated.Models.TestPageInvariantContentResponseModel"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::UmbracoDeliveryClient.Generated.Models.TestPageInvariantContentResponseModel? TestPageInvariantContentResponseModel { get; set; }
#nullable restore
#else
        public global::UmbracoDeliveryClient.Generated.Models.TestPageInvariantContentResponseModel TestPageInvariantContentResponseModel { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::UmbracoDeliveryClient.Generated.Models.IApiContentResponseModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::UmbracoDeliveryClient.Generated.Models.IApiContentResponseModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("contentType")?.GetStringValue();
            var result = new global::UmbracoDeliveryClient.Generated.Models.IApiContentResponseModel();
            if("testPage".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TestPageContentResponseModel = new global::UmbracoDeliveryClient.Generated.Models.TestPageContentResponseModel();
            }
            else if("testPageInvariant".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TestPageInvariantContentResponseModel = new global::UmbracoDeliveryClient.Generated.Models.TestPageInvariantContentResponseModel();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(TestPageContentResponseModel != null)
            {
                return TestPageContentResponseModel.GetFieldDeserializers();
            }
            else if(TestPageInvariantContentResponseModel != null)
            {
                return TestPageInvariantContentResponseModel.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(TestPageContentResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.TestPageContentResponseModel>(null, TestPageContentResponseModel);
            }
            else if(TestPageInvariantContentResponseModel != null)
            {
                writer.WriteObjectValue<global::UmbracoDeliveryClient.Generated.Models.TestPageInvariantContentResponseModel>(null, TestPageInvariantContentResponseModel);
            }
        }
    }
}
#pragma warning restore CS0618
