//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace umbraco.editorControls.imagecropper
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Obsolete("IDataType and all other references to the legacy property editors are no longer used this will be removed from the codebase in future versions")]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("umbraco.editorControls.imagecropper.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function initImageCropper(imageId, jsonId, rawId) {
        ///  $(function() {
        ///    $(&apos;.header a&apos;).click(function() {
        ///      initJcrop(imageId, jsonId, rawId); // if other tab
        ///    });
        ///    $(&apos;#&apos; + imageId).ready(function() {
        ///      setTimeout(&apos;initJcrop(&quot;&apos; + imageId + &apos;&quot;,&quot;&apos; + jsonId + &apos;&quot;,&quot;&apos; + rawId + &apos;&quot;)&apos;,100); 
        ///      //initJcrop(imageId, jsonId, rawId); // if first tab
        ///    });
        ///  });
        ///}
        ///
        ///function initJcrop(imageId, jsonId, rawId) {
        ///
        ///  if ($(&apos;#&apos; + imageId).height() &gt; 0) {
        ///    if ($(&apos;.img&apos; + imageId + &apos;.ic-cr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string imageCropperScript {
            get {
                return ResourceManager.GetString("imageCropperScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ////* Fixes issue here http://code.google.com/p/jcrop/issues/detail?id=1 */
        ///.jcrop-holder { text-align: left; }
        ///
        ///.jcrop-vline, .jcrop-hline
        ///{
        ///	font-size: 0;
        ///	position: absolute;
        ///	background: white url(&apos;/media/Jcrop.gif&apos;) top left repeat;
        ///}
        ///.jcrop-vline { height: 100%; width: 1px !important; }
        ///.jcrop-hline { width: 100%; height: 1px !important; }
        ///.jcrop-handle {
        ///	font-size: 1px;
        ///	width: 7px !important;
        ///	height: 7px !important;
        ///	border: 1px #eee solid;
        ///	background-color:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jCropCSS {
            get {
                return ResourceManager.GetString("jCropCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * jquery.Jcrop.js v0.9.8
        /// * jQuery Image Cropping Plugin
        /// * @author Kelly Hallman &lt;khallman@gmail.com&gt;
        /// * Copyright (c) 2008-2009 Kelly Hallman - released under MIT License {{{
        /// *
        /// * Permission is hereby granted, free of charge, to any person
        /// * obtaining a copy of this software and associated documentation
        /// * files (the &quot;Software&quot;), to deal in the Software without
        /// * restriction, including without limitation the rights to use,
        /// * copy, modify, merge, publish, distribute, sublicense, and/or s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jCropScript {
            get {
                return ResourceManager.GetString("jCropScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///    http://www.JSON.org/json2.js
        ///    2008-11-19
        ///
        ///    Public Domain.
        ///
        ///    NO WARRANTY EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.
        ///
        ///    See http://www.JSON.org/js.html
        ///
        ///    This file creates a global JSON object containing two methods: stringify
        ///    and parse.
        ///
        ///        JSON.stringify(value, replacer, space)
        ///            value       any JavaScript value, usually an object or array.
        ///
        ///            replacer    an optional parameter that determines how object
        ///                        values are st [rest of string was truncated]&quot;;.
        /// </summary>
        public static string json2Script {
            get {
                return ResourceManager.GetString("json2Script", resourceCulture);
            }
        }
    }
}