[
    'lib/jquery/jquery.min.js',
    'lib/angular/angular.min.js',
    'lib/underscore/underscore-min.js',
    'lib/umbraco/Extensions.js',
    'js/utilities.min.js',
    'js/app.min.js',
    'js/umbraco.resources.min.js',
    'js/umbraco.services.min.js',
    'js/umbraco.interceptors.min.js',
    'ServerVariables',
    'lib/signalr/signalr.min.js',
    'js/umbraco.preview.min.js'
]
