export type UmbEntityDataPickerPickerViewsConfigurationPropertyValue =
	Array<UmbEntityDataPickerPickerViewsConfigurationPropertyValueEntry>;

export interface UmbEntityDataPickerPickerViewsConfigurationPropertyValueEntry {
	alias: string;
}
