tinyMCE.addI18n('de.xhtmlxtras_dlg',{
attribute_label_title:"Titel",
attribute_label_id:"ID",
attribute_label_class:"Klasse",
attribute_label_style:"Format",
attribute_label_cite:"Quellenangabe",
attribute_label_datetime:"Zeit/Datum",
attribute_label_langdir:"Schriftrichtung",
attribute_option_ltr:"Links nach rechts",
attribute_option_rtl:"Rechts nach links",
attribute_label_langcode:"Sprache",
attribute_label_tabindex:"Tabindex",
attribute_label_accesskey:"Tastenk\u00FCrzel",
attribute_events_tab:"Ereignisse",
attribute_attrib_tab:"Attribute",
general_tab:"Allgemein",
attrib_tab:"Attribute",
events_tab:"Ereignisse",
fieldset_general_tab:"Allgemeine Einstellungen",
fieldset_attrib_tab:"Attribute",
fieldset_events_tab:"Ereignisse",
title_ins_element:"Eingef\u00FCgter Text",
title_del_element:"Entfernter Text",
title_acronym_element:"Akronym",
title_abbr_element:"Abk\u00FCrzung",
title_cite_element:"Quellenangabe",
remove:"Entfernen",
insert_date:"Aktuelle Zeit/Datum einf\u00FCgen",
option_ltr:"Links nach rechts",
option_rtl:"Rechts nach links",
attribs_title:"Attribute einf\u00FCgen/bearbeiten"
});