using Umbraco.Cms.Core.DependencyInjection;

namespace Umbraco.Cms.Api.Common.OpenApi;

/// <summary>
/// Extension methods for <see cref="IUmbracoBuilder"/> to register custom OpenAPI documents.
/// </summary>
public static class UmbracoBuilderOpenApiExtensions
{
    /// <summary>
    /// Registers a custom OpenAPI document with Umbraco's defaults applied.
    /// </summary>
    /// <param name="builder">The Umbraco builder.</param>
    /// <param name="documentName">The document name. Matches the <c>[MapToApi]</c> value on controllers to include.</param>
    /// <param name="configure">Optional callback to customize the document.</param>
    /// <returns>The same <see cref="IUmbracoBuilder"/> for chaining.</returns>
    /// <remarks>
    /// <para>
    /// The following defaults are applied to the document and can be customized or overridden via the
    /// <paramref name="configure"/> callback:
    /// </para>
    /// <list type="bullet">
    ///   <item>
    ///     <description>
    ///     Endpoints are filtered by <c>[MapToApi(documentName)]</c>; only matching endpoints appear in the document.
    ///     </description>
    ///   </item>
    ///   <item>
    ///     <description>
    ///     Schema reference IDs are generated by <see cref="UmbracoSchemaIdGenerator.CreateSchemaReferenceId"/>, applying
    ///     Umbraco naming conventions to types under the <c>Umbraco.Cms</c> namespace and falling back to the framework
    ///     default for everything else. Register your own <c>CreateSchemaReferenceId</c> delegate via
    ///     <see cref="BackOfficeOpenApiDocumentBuilder.ConfigureOpenApiOptions"/> to override.
    ///     </description>
    ///   </item>
    ///   <item>
    ///     <description>
    ///     Operation IDs are generated by <see cref="UmbracoOperationIdTransformer"/>. Register your own
    ///     <see cref="Microsoft.AspNetCore.OpenApi.IOpenApiOperationTransformer"/> via
    ///     <see cref="BackOfficeOpenApiDocumentBuilder.ConfigureOpenApiOptions"/> to override.
    ///     </description>
    ///   </item>
    ///   <item>
    ///     <description>
    ///     Operations are tagged by their controller's API group name, and the resulting tags and paths are sorted
    ///     for stable, diffable document output.
    ///     </description>
    ///   </item>
    ///   <item>
    ///     <description>
    ///     The document is registered in the OpenAPI UI document selector dropdown. Call
    ///     <see cref="BackOfficeOpenApiDocumentBuilder.ExcludeFromUi"/> to opt out.
    ///     </description>
    ///   </item>
    /// </list>
    /// </remarks>
    public static IUmbracoBuilder AddBackOfficeOpenApiDocument(
        this IUmbracoBuilder builder,
        string documentName,
        Action<BackOfficeOpenApiDocumentBuilder>? configure = null)
    {
        var documentBuilder = new BackOfficeOpenApiDocumentBuilder(documentName);
        configure?.Invoke(documentBuilder);
        documentBuilder.Build(builder);
        return builder;
    }
}
