#!/bin/bash
# Trusts the self-signed certificate generated by the Umbraco Docker container.
# Run this once after the first `docker compose up` to stop browser HTTPS warnings.
# Requires sudo on macOS and Linux.

CERT="$(dirname "$0")/certs/aspnetcore.crt"

if [ ! -f "$CERT" ]; then
    echo "Certificate not found at $CERT"
    echo "Start the container first with: docker compose up"
    exit 1
fi

case "$(uname -s)" in
    Darwin)
        sudo security add-trusted-cert -d -r trustRoot \
            -k /Library/Keychains/System.keychain "$CERT"
        echo "Certificate trusted. Restart your browser for changes to take effect."
        ;;
    Linux)
        sudo cp "$CERT" /usr/local/share/ca-certificates/umbraco-dev.crt
        sudo update-ca-certificates
        echo "Certificate trusted. Restart your browser for changes to take effect."
        ;;
    *)
        echo "Unsupported OS. On Windows, run trust-cert.ps1 instead."
        exit 1
        ;;
esac
