<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Umbraco CMS - Search - File to text extension</Title>
    <Description>Extends Umbraco Search with indexing of the text contents of files (such as PDF, Markdown and text files) referenced by file properties (such as file upload and image cropper properties).</Description>
    <PackageTags>umbraco search pdf</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Umbraco.Cms.Search.Core\Umbraco.Cms.Search.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Umbraco.Tests.Integration</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
