using System;

namespace Umbraco.Core.Media
{
    // note: because this interface is obsolete is is *not* IDiscoverable, and in case the
    // PluginManager is asked to find types implementing this interface it will fall back
    // to a complete scan.

    [Obsolete("Thumbnails are generated by ImageProcessor, use that instead")]
	public interface IThumbnailProvider  // : IDiscoverable
    {
        bool CanProvideThumbnail(string fileUrl);
        string GetThumbnailUrl(string fileUrl);
    }

}
