// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44324' | (string & {});
};

export type DocumentModel = {
    key: string;
    documents: Array<IndexDocumentModel>;
};

export type FieldModel = {
    name: string;
    type?: string | null;
    values: Array<string>;
};

export type IndexDocumentModel = {
    fields: Array<FieldModel>;
};

export type GetDocumentData = {
    body?: never;
    path: {
        indexAlias: string;
        documentKey: string;
    };
    query?: never;
    url: '/umbraco/examine/api/v1/{indexAlias}/document/{documentKey}';
};

export type GetDocumentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetDocumentResponses = {
    /**
     * OK
     */
    200: DocumentModel;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];
