import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const loginDir = resolve(here, '../..');
const clientDir = resolve(loginDir, '../Umbraco.Web.UI.Client');
const tsconfigPath = resolve(loginDir, 'tsconfig.json');

const tsconfigComment = `
/* -------------------------------------------------------------------------


DON'T EDIT THIS FILE DIRECTLY. It is generated by /devops/tsconfig/index.js


--------------------------------------------------------------------------- */
`;

const clientPkg = JSON.parse(readFileSync(resolve(clientDir, 'package.json'), 'utf8'));

const paths = {};

for (const [subpath, target] of Object.entries(clientPkg.exports ?? {})) {
	if (target === null) continue; // The `.` self-reference.
	if (!subpath.startsWith('./')) continue;
	if (typeof target !== 'string') {
		throw new Error(
			`Unsupported exports entry for "${subpath}" in ${clientPkg.name}: expected a string target, got ${typeof target}. ` +
				`Update the generator to handle conditional exports.`,
		);
	}

	const aliasKey = `${clientPkg.name}/${subpath.slice(2)}`;
	const sourceTarget = target
		.replace(/^\.\/dist-cms\//, '../Umbraco.Web.UI.Client/src/')
		.replace(/\.d\.ts$/, '.ts')
		.replace(/\.js$/, '.ts');
	paths[aliasKey] = [sourceTarget];
}

const tsConfig = {
	compilerOptions: {
		target: 'ES2024',
		module: 'ESNext',
		lib: ['ES2024', 'DOM', 'DOM.Iterable'],
		experimentalDecorators: true,
		useDefineForClassFields: false,
		moduleResolution: 'bundler',
		skipLibCheck: true,
		allowImportingTsExtensions: true,
		resolveJsonModule: true,
		isolatedModules: true,
		noEmit: true,
		strict: true,
		noFallthroughCasesInSwitch: true,
		noImplicitReturns: true,
		paths,
	},
	include: ['src'],
};

const content = tsconfigComment + JSON.stringify(tsConfig, null, '\t') + '\n';
const existing = existsSync(tsconfigPath) ? readFileSync(tsconfigPath, 'utf8') : null;

if (existing === content) {
	console.log(`tsconfig.json already up to date (${Object.keys(paths).length} path aliases)`);
} else {
	writeFileSync(tsconfigPath, content);
	console.log(`Wrote ${Object.keys(paths).length} path aliases to ${tsconfigPath}`);
}
