import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const loginDir = resolve(here, '../..');
const clientDir = resolve(loginDir, '../Umbraco.Web.UI.Client');
const tsconfigPath = resolve(loginDir, 'tsconfig.json');

const tsconfigComment = `
/* -------------------------------------------------------------------------


DON'T EDIT THIS FILE DIRECTLY. It is generated by /devops/tsconfig/index.js


Path aliases mirror the @umbraco-cms/backoffice/* exports map of the sibling
Umbraco.Web.UI.Client and resolve to its TypeScript source so tsc can type-check
without needing a built dist-cms. Runtime resolution is unaffected — vite still
externalises /^@umbraco-cms/ and the host page's importmap serves the real JS.


--------------------------------------------------------------------------- */
`;

const clientPkg = JSON.parse(readFileSync(resolve(clientDir, 'package.json'), 'utf8'));

const paths = {};

for (const [subpath, target] of Object.entries(clientPkg.exports ?? {})) {
	// Skip non-string entries (the `.` self-reference is `null` in Client's manifest).
	if (typeof target !== 'string') continue;
	// Only map subpaths under @umbraco-cms/backoffice/*.
	if (!subpath.startsWith('./')) continue;

	const aliasKey = `${clientPkg.name}/${subpath.slice(2)}`;
	// Rewrite ./dist-cms/<rest>(.js|.d.ts) → ../Umbraco.Web.UI.Client/src/<rest>.ts
	const sourceTarget = target
		.replace(/^\.\/dist-cms\//, '../Umbraco.Web.UI.Client/src/')
		.replace(/\.d\.ts$/, '.ts')
		.replace(/\.js$/, '.ts');
	paths[aliasKey] = [sourceTarget];
}

const tsConfig = {
	compilerOptions: {
		target: 'ES2024',
		module: 'ESNext',
		lib: ['ES2024', 'DOM', 'DOM.Iterable'],
		experimentalDecorators: true,
		useDefineForClassFields: false,
		moduleResolution: 'bundler',
		skipLibCheck: true,
		allowImportingTsExtensions: true,
		resolveJsonModule: true,
		isolatedModules: true,
		noEmit: true,
		strict: true,
		noFallthroughCasesInSwitch: true,
		noImplicitReturns: true,
		paths,
	},
	include: ['src'],
};

const content = tsconfigComment + JSON.stringify(tsConfig, null, '\t') + '\n';
const existing = existsSync(tsconfigPath) ? readFileSync(tsconfigPath, 'utf8') : null;

if (existing === content) {
	console.log(`tsconfig.json already up to date (${Object.keys(paths).length} path aliases)`);
} else {
	writeFileSync(tsconfigPath, content);
	console.log(`Wrote ${Object.keys(paths).length} path aliases to ${tsconfigPath}`);
}
