name: big-pr-resonse

on:
  pull_request:
    types: [opened]
    branches:
      - contrib

env:
  sweeping_pr_filecount: 10

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check if PR is big
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;

            const response = await fetch('https://collaboratorsv2.euwest01.umbraco.io/umbraco/api/users/GetIgnoredUsers', {
              method: 'POST',
              headers: {
                'Authorization': 'Bearer ${{ secrets.OUR_BOT_API_TOKEN }}',
                'Content-Type': 'application/json'
              }
            });

            const hqUsers = await response.json();

            if(hqUsers.includes(pr.head.user.login)) {
              console.log(`User ${pr.head.user.login} is from HQ`);
              return;
            }

            console.log(`User ${pr.head.user.login} is not from HQ`);

            const fileCount = pr.changed_files;

            console.log(`PR #${pr.number} has ${fileCount} changed files`);

            if (fileCount < ${{ env.sweeping_pr_filecount }}) {
              return;
            }

            const comment = `
            > [!NOTE]
            > This is a :cut_of_meat: **MEATY PR** :cut_of_meat: with ${fileCount} files changed.
            `;

            github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
